### ISSUE TITLE
[OpenKAT v1.7] Failure mode writing raw files

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#136]
We should either:

- ~Give feedback in the mime-types by adding "error" in Bytes~
- ~Or pass the file writing exception to the boefje handler and update the boefje meta with an error there.~
Update:
-  As @jpbruinsslot mentioned: the scheduler API has a PATCHJ endpoint for Tasks. This means that we can hand the responsibility to update the task status over to the JobHandler, which I think would be the cleanest solution: if you handle a task, you should update its state. I would even opt for setting the status to "completed" in the JobHandler instead of waiting for a signal from Bytes. The Signal can still be used to trigger new jobs of course.

Example of such a stack trace in Bytes:

```
[2023-01-11 13:30:26 +0000] [10] [INFO] [sql_meta_repository] Saving raw 
[2023-01-11 13:30:26 +0000] [10] [INFO] [sql_meta_repository] Added hash sha512:8f33266b32db49745efc9444e66c17218961a9f5594623369b910637487de30ba36c70c7a3f65c7e331acdb575b8bd1efabb8131e7948427790b897c0b6ee113 and link 35f75a10-56b1-44c1
-9c86-3fe6935673b7 to data 
[2023-01-11 13:30:26 +0000] [10] [ERROR] [router] Error saving raw data: [Errno 13] Permission denied: '/app/bytes/bytes-data' 
Traceback (most recent call last): 
 File "/app/bytes/./bytes/api/v2/router.py", line 124, in create_raw 
   raw_id = meta_repository.save_raw(raw_data) 
 File "/app/bytes/./bytes/database/sql_meta_repository.py", line 109, in save_raw 
   self.raw_repository.save_raw(raw_file_in_db.id, raw) 
 File "/app/bytes/./bytes/raw/file_raw_repository.py", line 43, in save_raw 
   parent.mkdir(exist_ok=True, mode=self._folder_permissions) 
 File "/usr/local/lib/python3.8/pathlib.py", line 1288, in mkdir 
   self._accessor.mkdir(self, mode) 
PermissionError: [Errno 13] Permission denied: '/app/bytes/bytes-data' 
[2023-01-11 13:30:26 +0000] [10] [INFO] [sql_meta_repository] Committing session 
[2023-01-11 13:30:26 +0000] [10] [ERROR] [sql_meta_repository] An error occured: . Rolling back session 
Traceback (most recent call last): 
 File "/app/bytes/./bytes/api/v2/router.py", line 124, in create_raw 
   raw_id = meta_repository.save_raw(raw_data) 
 File "/app/bytes/./bytes/database/sql_meta_repository.py", line 109, in save_raw 
   self.raw_repository.save_raw(raw_file_in_db.id, raw) 
 File "/app/bytes/./bytes/raw/file_raw_repository.py", line 43, in save_raw 
   parent.mkdir(exist_ok=True, mode=self._folder_permissions) 
 File "/usr/local/lib/python3.8/pathlib.py", line 1288, in mkdir 
   self._accessor.mkdir(self, mode) 
PermissionError: [Errno 13] Permission denied: '/app/bytes/bytes-data' 

The above exception was the direct cause of the following exception: 

Traceback (most recent call last): 
 File "/app/bytes/./bytes/database/sql_meta_repository.py", line 183, in create_meta_data_repository 
   yield repository 
fastapi.exceptions.HTTPException
```

And we cannot create a Bytes file of the stack trace since we have not permissions.

**Comment by Donnype** [comment]
@underdarknl Check out the update!
