### ISSUE TITLE
Rate limiting accros multi-organisations/workers.

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1436]
**Describe the bug**
Some boefjes require an external API. When multiple boefjes use the same API at the same time (e.g. organisation A, B and C require data from the same external API at the same moment) rate limiting can occur, resulting in failed boefjes.

**To Reproduce**
1. Create multiple organisations with multiple assets
2. Add a Shodan API key and enable boefje
3. Notice failing Shodan boefjes can occur due to rate limiting:

```nomad
[2023-07-24 08:38:50 +0000] [9] [ERROR] [job_handler] Error running boefje shodan[c76577ac40df4364bcd6f4d9c59738da]
Traceback (most recent call last):
  File "/app/boefjes/boefjes/local.py", line 50, in run
    return boefje_resource.module.run(boefje_meta)
  File "/app/boefjes/boefjes/plugins/kat_shodan/main.py", line 22, in run
    results = api.host(ip)
  File "/usr/local/lib/python3.8/site-packages/shodan/client.py", line 380, in host
    return self._request('/shodan/host/%s' % ','.join(ips), params)
  File "/usr/local/lib/python3.8/site-packages/shodan/client.py", line 340, in _request
    raise APIError(data['error'])
shodan.exception.APIError: Rate limit reached. Please throttle your requests to 1 request per second.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/boefjes/boefjes/job_handler.py", line 138, in handle
    boefje_results = self.job_runner.run(boefje_meta, environment)
  File "/app/boefjes/boefjes/local.py", line 52, in run
    raise JobRuntimeError("Boefje failed") from e
boefjes.runtime_interfaces.JobRuntimeError: Boefje failed
```

**Expected behavior**
Some kind of intelligence in the KAT installation to not start boefjes with a dependence on the same external API at the same time (e.g. across multiple organizations or workers). This is probably a scheduling issue that gets more likely to occur with every organization added.

**OpenKAT version**
1.8

**Comment by underdarknl** [comment]
https://github.com/minvws/nl-kat-coordination/issues/1317 should tackle these issues.
