### ISSUE TITLE
Crisis room unable to fetch findings for some organisations

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1449]
**Describe the bug**
![image](https://github.com/minvws/nl-kat-coordination/assets/115991818/e4476a74-cfa0-49fa-abf6-d48a8f81b886)

**To Reproduce**
1. Have some organisations with findings
2. Go to crisis room
3. See error for some organisations

**Expected behavior**
No error

**Logs**
```nomad
Failed to get list of findings for organization [organisation]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/octopoes/connector/octopoes.py", line 42, in _verify_response
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://octopoes-api.service.consul:8000/[organisation]/findings/count_by_severity?valid_time=2023-07-25+08%3A32%3A22.209243%2B00%3A00

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/rocky/crisis_room/views.py", line 68, in get_finding_type_severity_count
    return api_connector.count_findings_by_severity(valid_time=self.get_observed_at())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/octopoes/connector/octopoes.py", line 185, in count_findings_by_severity
    res = self.session.get(f"/{self.client}/findings/count_by_severity", params=params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/octopoes/connector/octopoes.py", line 62, in request
    self._verify_response(response)
  File "/usr/local/lib/python3.11/site-packages/octopoes/connector/octopoes.py", line 49, in _verify_response
    raise RemoteException(value=data["value"])
octopoes.connector.RemoteException: TypeError: argument of type 'NoneType' is not iterable
```

**OpenKAT version**
1.10.0rc2

**Comment by sigio** [comment]
Stacktrace:
```
Aug 01 14:14:46 octopoes.acc.kat.prolocation.net python3[1588714]: [2023-08-01 14:14:46 +0200] [1588714] [ERROR] [h11_impl] Exception in ASGI application
                                                                   Traceback (most recent call last):
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
                                                                       result = await app(  # type: ignore[func-returns-value]
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
                                                                       return await self.app(scope, receive, send)
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
                                                                       raise exc from None
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
                                                                       await self.app(scope, inner_receive, inner_send)
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/fastapi/applications.py", line 274, in __call__
                                                                       await super().__call__(scope, receive, send)
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/starlette/applications.py", line 118, in __call__
                                                                       await self.middleware_stack(scope, receive, send)
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
                                                                       raise exc
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
                                                                       await self.app(scope, receive, _send)
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 108, in __call__
                                                                       response = await self.dispatch_func(request, call_next)
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/fastapi_utils/timing.py", line 47, in timing_middleware
                                                                       response = await call_next(request)
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 84, in call_next
                                                                       raise app_exc
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 70, in coro
                                                                       await self.app(scope, receive_or_disconnect, send_no_error)
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
                                                                       raise exc
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
                                                                       await self.app(scope, receive, sender)
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
                                                                       raise e
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
                                                                       await self.app(scope, receive, send)
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/starlette/routing.py", line 706, in __call__
                                                                       await route.handle(scope, receive, send)
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
                                                                       await self.app(scope, receive, send)
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
                                                                       response = await func(request)
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 238, in app
                                                                       raw_response = await run_endpoint_function(
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 166, in run_endpoint_function
                                                                       return await run_in_threadpool(dependant.call, **values)
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
                                                                       return await anyio.to_thread.run_sync(func, *args)
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
                                                                       return await get_asynclib().run_sync_in_worker_thread(
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
                                                                       return await future
                                                                     File "/var/www/html/.venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
                                                                       result = context.run(func, *args)
                                                                     File "/var/www/octopoes_v1.10.0/./octopoes/api/router.py", line 350, in get_finding_type_count
                                                                       return octopoes.ooi_repository.count_findings_by_severity(valid_time)
                                                                     File "/var/www/octopoes_v1.10.0/./octopoes/repositories/ooi_repository.py", line 594, in count_findings_by_severity
                                                                       ft = cast(FindingType, self.deserialize(finding_type))
                                                                     File "/var/www/octopoes_v1.10.0/./octopoes/repositories/ooi_repository.py", line 202, in deserialize
                                                                       if "object_type" not in data:
                                                                   TypeError: argument of type 'NoneType' is not iterable
```
