### ISSUE TITLE
CVE Finding types normalizer KeyError

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1485]
**Describe the bug**
CVEFinding normalizer fails with a KeyError

**To Reproduce**
1. Run CVEFindingTypes boefje
2. Notice boefje is completed
3. Notice normalizer fails with below error.

**Expected behavior**
No KeyError

**Logs**
```nomad
[2023-07-27 12:11:34 +0000] [7] [INFO] [job_handler] Handling normalizer kat_cve_finding_types_normalize[da90f19f0f144a1187afaa59f6c11cc6]
[2023-07-27 12:11:34 +0000] [7] [INFO] [local] Running local normalizer plugin
[2023-07-27 12:11:34 +0000] [7] [ERROR] [app] An error occurred handling scheduler item da90f19f0f144a1187afaa59f6c11cc6
Traceback (most recent call last):
  File "/app/boefjes/boefjes/app.py", line 105, in start_working
    item_handler.handle(p_item.data)
  File "/app/boefjes/boefjes/job_handler.py", line 183, in handle
    results = self.job_runner.run(normalizer_meta, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/boefjes/boefjes/local.py", line 73, in run
    return self._parse_results(normalizer_meta, results)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/boefjes/boefjes/local.py", line 76, in _parse_results
    parsed: List[NormalizerResult] = [self._parse(result) for result in results]
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/boefjes/boefjes/local.py", line 76, in <listcomp>
    parsed: List[NormalizerResult] = [self._parse(result) for result in results]
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/boefjes/boefjes/plugins/kat_cve_finding_types/normalize.py", line 45, in run
    cvss = metrics["cvssMetricV20"]
           ~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'cvssMetricV20'
```

**OpenKAT version**
1.10.0rc2

**Comment by dekkers** [comment]
Which CVE is this?
