### ISSUE TITLE
Exception on main branch: AttributeError: module 'qrcode.image.base' has no attribute 'BaseImageWithDrawer'

### ISSUE THREAD

**Issue by praseodym** [minvws/nl-kat-coordination#1641]
```
Aug 21 15:20:44 debian12 kat-rocky[870]: [pid: 870|app: 0|req: 19/19] 127.0.0.1 () {48 vars in 903 bytes} [Mon Aug 21 13:20:43 2023] GET /en/mispoes/objects/ => generated 0 bytes in 145 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 6)
Aug 21 15:20:44 debian12 kat-rocky[870]: Traceback (most recent call last):
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "/opt/venvs/kat-rocky/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
Aug 21 15:20:44 debian12 kat-rocky[870]:     response = get_response(request)
Aug 21 15:20:44 debian12 kat-rocky[870]:                ^^^^^^^^^^^^^^^^^^^^^
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "/opt/venvs/kat-rocky/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
Aug 21 15:20:44 debian12 kat-rocky[870]:     response = self.process_request(request)
Aug 21 15:20:44 debian12 kat-rocky[870]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "/opt/venvs/kat-rocky/lib/python3.11/site-packages/django/middleware/locale.py", line 24, in process_request
Aug 21 15:20:44 debian12 kat-rocky[870]:     ) = is_language_prefix_patterns_used(urlconf)
Aug 21 15:20:44 debian12 kat-rocky[870]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "/opt/venvs/kat-rocky/lib/python3.11/site-packages/django/conf/urls/i18n.py", line 31, in is_language_prefix_patterns_used
Aug 21 15:20:44 debian12 kat-rocky[870]:     for url_pattern in get_resolver(urlconf).url_patterns:
Aug 21 15:20:44 debian12 kat-rocky[870]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "/opt/venvs/kat-rocky/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
Aug 21 15:20:44 debian12 kat-rocky[870]:     res = instance.__dict__[self.name] = self.func(instance)
Aug 21 15:20:44 debian12 kat-rocky[870]:                                          ^^^^^^^^^^^^^^^^^^^
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "/opt/venvs/kat-rocky/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
Aug 21 15:20:44 debian12 kat-rocky[870]:     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
Aug 21 15:20:44 debian12 kat-rocky[870]:                        ^^^^^^^^^^^^^^^^^^^
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "/opt/venvs/kat-rocky/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
Aug 21 15:20:44 debian12 kat-rocky[870]:     res = instance.__dict__[self.name] = self.func(instance)
Aug 21 15:20:44 debian12 kat-rocky[870]:                                          ^^^^^^^^^^^^^^^^^^^
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "/opt/venvs/kat-rocky/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
Aug 21 15:20:44 debian12 kat-rocky[870]:     return import_module(self.urlconf_name)
Aug 21 15:20:44 debian12 kat-rocky[870]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
Aug 21 15:20:44 debian12 kat-rocky[870]:     return _bootstrap._gcd_import(name[level:], package, level)
Aug 21 15:20:44 debian12 kat-rocky[870]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "/opt/venvs/kat-rocky/lib/python3.11/site-packages/rocky/urls.py", line 7, in <module>
Aug 21 15:20:44 debian12 kat-rocky[870]:     from two_factor.urls import urlpatterns as tf_urls
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "/opt/venvs/kat-rocky/lib/python3.11/site-packages/two_factor/urls.py", line 4, in <module>
Aug 21 15:20:44 debian12 kat-rocky[870]:     from two_factor.views import (
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "/opt/venvs/kat-rocky/lib/python3.11/site-packages/two_factor/views/__init__.py", line 1, in <module>
Aug 21 15:20:44 debian12 kat-rocky[870]:     from .core import (
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "/opt/venvs/kat-rocky/lib/python3.11/site-packages/two_factor/views/core.py", line 11, in <module>
Aug 21 15:20:44 debian12 kat-rocky[870]:     import qrcode.image.svg
Aug 21 15:20:44 debian12 kat-rocky[870]:   File "/opt/venvs/kat-rocky/lib/python3.11/site-packages/qrcode/image/svg.py", line 13, in <module>
Aug 21 15:20:44 debian12 kat-rocky[870]:     class SvgFragmentImage(qrcode.image.base.BaseImageWithDrawer):
Aug 21 15:20:44 debian12 kat-rocky[870]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 21 15:20:44 debian12 kat-rocky[870]: AttributeError: module 'qrcode.image.base' has no attribute 'BaseImageWithDrawer'
```

**Comment by praseodym** [comment]
Caused by not restarting rocky after upgrading.
