### ISSUE TITLE
Disabling Bit via environment does not work 

### ISSUE THREAD

**Issue by tobiasBDO** [minvws/nl-kat-coordination#1710]
**Describe the bug**
While browsing the docs I found out there are a lot of different interesting environment variables available,[ such as this one](https://docs.openkat.nl/technical_design/environment_settings/octopoes.html#octopoes-bits-disabled). Disabling bits via the Environment, but this does not seem to work,.

**To Reproduce**
1. `make env`
2. Add `OCTOPOES_BITS_DISABLED={"port-classification-bit"}` to your env
3. `make up` or `docker-compose -f docker-compose.release-example.yml up -d`
4. Wait for logs

**Expected behavior**
I expected this environment variable to be added and interpreted by Octopoes.

**Screenshots**
```python
INFO:     Will watch for changes in these directories: ['/app/octopoes/octopoes']
INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
INFO:     Started reloader process [1] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "pydantic/env_settings.py", line 198, in pydantic.env_settings.EnvSettingsSource.__call__
  File "pydantic/env_settings.py", line 132, in pydantic.env_settings.Config.parse_env_var
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 27 (char 26)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/octopoes/octopoes/api/api.py", line 23, in <module>
    from octopoes.api.router import router
  File "/app/octopoes/octopoes/api/router.py", line 19, in <module>
    from octopoes.core.app import bootstrap_octopoes, get_xtdb_client
  File "/app/octopoes/octopoes/core/app.py", line 6, in <module>
    from octopoes.core.service import OctopoesService
  File "/app/octopoes/octopoes/core/service.py", line 51, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "pydantic/env_settings.py", line 41, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/env_settings.py", line 76, in pydantic.env_settings.BaseSettings._build_values
  File "pydantic/env_settings.py", line 201, in pydantic.env_settings.EnvSettingsSource.__call__
pydantic.env_settings.SettingsError: error parsing env var "octopoes_bits_disabled"
```

**OpenKAT version**
OpenKAT v1.11.0

**Comment by praseodym** [comment]
Could you verify that `OCTOPOES_BITS_DISABLED=["port-classification-ip"]` works as expected? In the example, both the syntax and the bit name are incorrect.

If my suggestion works, I'll update the documentation with the correct syntax.

**Comment by tobiasBDO** [comment]
> Could you verify that `OCTOPOES_BITS_DISABLED=["port-classification-ip"]` works as expected? In the example, both the syntax and the bit name are incorrect.
> 
> If my suggestion works, I'll update the documentation with the correct syntax.

Beautiful, and after a rerun of all bits the excluded ones' findings are also removed. So quick update of the docs would solve this!
