### ISSUE TITLE
Scheduler gets timeouts requesting token from Bytes

### ISSUE THREAD

**Issue by jpbruinsslot** [minvws/nl-kat-coordination#1797]
```
Could not check if task is running: id='8b9ad66acf63429aa5a3daf2a289200b' boefje=Boefje(id='dns-sec', version=None) input_ooi='Hostname|internet|REDACTED' organization='REDACTED' dispatches=[] [organisation_id=REDACTED, scheduler_id=boefje-REDACTED, caller=push_tasks_for_new_boefjes]
Traceback (most recent call last):
  File "/var/www/scheduler_v1.11/scheduler/connectors/services/bytes.py", line 20, in wrapper
    return function(self, *args, **kwargs)
  File "/var/www/scheduler_v1.11/scheduler/connectors/errors.py", line 14, in inner_function
    return func(*args, **kwargs)
  File "/var/www/scheduler_v1.11/scheduler/connectors/services/bytes.py", line 87, in get_last_run_boefje
    self._verify_response(response)
  File "/var/www/scheduler_v1.11/scheduler/connectors/services/bytes.py", line 58, in _verify_response
    response.raise_for_status()
  File "/var/www/html/.venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: REDACTED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/html/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/var/www/html/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/html/.venv/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/var/www/html/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/var/www/html/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/var/www/html/.venv/lib/python3.8/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/var/www/html/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/var/www/html/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/var/www/html/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='REDACTED', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/scheduler_v1.11/scheduler/schedulers/boefje.py", line 501, in push_task
    is_running = self.is_task_running(task)
  File "/var/www/scheduler_v1.11/scheduler/schedulers/boefje.py", line 433, in is_task_running
    raise exc_bytes
  File "/var/www/scheduler_v1.11/scheduler/schedulers/boefje.py", line 418, in is_task_running
    task_bytes = self.ctx.services.bytes.get_last_run_boefje(
  File "/var/www/scheduler_v1.11/scheduler/connectors/services/bytes.py", line 25, in wrapper
    self.login()
  File "/var/www/scheduler_v1.11/scheduler/connectors/services/bytes.py", line 54, in login
    self.headers.update({"Authorization": f"bearer {self._get_token()}"})
  File "/var/www/scheduler_v1.11/scheduler/connectors/services/bytes.py", line 62, in _get_token
    response = self.post(
  File "/var/www/scheduler_v1.11/scheduler/connectors/services/services.py", line 137, in post
    response = self.session.post(
  File "/var/www/html/.venv/lib/python3.8/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/var/www/html/.venv/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/www/html/.venv/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/www/html/.venv/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='REDACTED', port=443): Read timed out. (read timeout=5)
```

**Comment by jpbruinsslot** [comment]
Did a test with lowering the `ACCESS_TOKEN_EXPIRE_MINUTES` to 30, wasn't seeing any timeouts but some of the posts to the `/token` endpoint took longer than 500 ms and some where in clusters. I'll continue to make a test where I create a high load within the scheduler and set the timeout shorter to see if multiple threads requesting the token might cause the bytes timeouts.

**Comment by jpbruinsslot** [comment]
Lower the `ACCESS_TOKEN_EXPIRE_MINUTES` to 1, and created a high load with ~1000 hostnames. Wasn't able to reproduce the specific issue. Bytes seems to handle the load correctly. Will investigate the headers hypotheses further with @Donnype

**Comment by jpbruinsslot** [comment]
This issue could be related: https://github.com/minvws/nl-kat-coordination/issues/1884

meaning the bytes host url might have path and could not be resolved correctly, however this would result in 404 not necessarily timeouts

**Comment by jpbruinsslot** [comment]
This is probably unrelated, but while debugging with @Donnype we tidied up the usage of the headers  in the following merged PR https://github.com/minvws/nl-kat-coordination/pull/1896

**Comment by jpbruinsslot** [comment]
While working on https://github.com/minvws/nl-kat-coordination/issues/1967 same indications as the issue here were observed while using the load tester script of https://github.com/minvws/nl-kat-coordination/pull/1993

Some observations:

* `connection pool is full` warnings are not necessarily a problem this is because the connection is being discarded after the request is completed, by default if a new request is made and there is no free connection in the pool then a new connection will be created. This connection is then not kept in the pool for later use. We likely want the pool as large as there are threads issuing http requests

* A lot of `POST /token` request are being handled by bytes, first it was thought to be the scheduler issuing all these requests. Upon further inspection (`docker inspect $(docker ps -q ) \
--format='{{ printf "%-50s" .Name}} {{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}}' `)  these requests stem from the boefje and normalizer runners.

* Bytes doesn't seem to be the cpu/mem bottleneck, the highest loads were observed at the `octopoes_api_worker` and `crux_db`.

* The timeout problem on the `/token` endpoint from the scheduler. This can be mitigated by increasing the timeout to 10 seconds from 5.

**Comment by jpbruinsslot** [comment]
From the above observations the following PR has been created: https://github.com/minvws/nl-kat-coordination/pull/1999

**Comment by jpbruinsslot** [comment]
Additionally changes in the boefjes and normalizer runner have been implemented in the following PR: https://github.com/minvws/nl-kat-coordination/pull/2019

**Comment by jpbruinsslot** [comment]
Closing for now, the specific issue has not been seen in a while
