### ISSUE TITLE
Scheduler experiences rabbitmq issues

### ISSUE THREAD

**Issue by jpbruinsslot** [minvws/nl-kat-coordination#1967]
1. Scheduler experiences rabbitmq issues in a multi-node rabbitmq infrastructure or rabbitmq running behind a round-robin dns load balancer. Threads trying to re-use connections that are non-existent.

2. Additionally, in Rabbitmq 3.5.5 the broker's default heartbeat timeout is decreased from 580 seconds to 60 seconds which can result in Blocked Connection Timeouts when the connection has been blocked longer than the given timeout value.

For the first issue, a solution could be creating a connection recovery mechanism.[^1] For the second issue the potential solution can be to delegate processing of the incoming messages to another thread, now we acknowledge the message after the message has been processed, this can potentially take longer than the heartbeat timeout resulting in blocked connection timeouts.[^2] A workaround to increase the heartbeat timeout can be done by setting this in the url parameters of rabbitmq[^3][^4]

Observed errors in the scheduler which indicate above issues:

```
[2023-10-25 12:53:33 +0000] [ERROR] [scheduler.utils.thread] Exception in thread: Thread-44 (listen)-scheduler-normalizer-246-raw_file
Traceback (most recent call last):
  File "/app/scheduler/scheduler/utils/thread.py", line 79, in run_once
    self._target()
  File "/app/scheduler/scheduler/connectors/listeners/raw_data.py", line 34, in listen
    self.basic_consume(self.queue, True, self.prefetch_count)
  File "/app/scheduler/scheduler/connectors/listeners/listeners.py", line 84, in basic_consume
    self.channel.start_consuming()
  File "/usr/local/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/usr/local/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/usr/local/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 851, in process_data_events
    self._dispatch_channel_events()
  File "/usr/local/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 567, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/local/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 1510, in _dispatch_events
    consumer_info.on_message_callback(self, evt.method,
  File "/app/scheduler/scheduler/connectors/listeners/listeners.py", line 109, in callback
    self.dispatch(body)
  File "/app/scheduler/scheduler/connectors/listeners/raw_data.py", line 45, in dispatch
    self.func(model)
  File "/app/scheduler/scheduler/schedulers/normalizer.py", line 124, in push_tasks_for_received_raw_data
    executor.submit(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```

[^1]: https://pika.readthedocs.io/en/stable/examples/blocking_consume_recover_multiple_hosts.html
[^2]: https://pika.readthedocs.io/en/stable/modules/adapters/index.html#requesting-message-acknowledgements-from-another-thread
[^3]: https://pika.readthedocs.io/en/stable/examples/using_urlparameters.html#example-connection-urls
[^4]: https://pika.readthedocs.io/en/stable/examples/heartbeat_and_blocked_timeouts.html

**Comment by jpbruinsslot** [comment]
@dekkers I've created the following issue https://github.com/minvws/nl-kat-coordination/issues/1992 from your observations
