### ISSUE TITLE
Handle unknown organisations in the katalogus with a descriptive 404 respons instead of a 500.

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#2128]
**Is your feature request related to a problem? Please describe.**
Currently the katalogus request crashes when asked for an nonexistent organization, possibly because of a non caught exception, or a not specific enough raise.

**Describe the solution you'd like**
Raise the specific exception `OrganisationNotFound`, or also catch the broader `ObjectNotFoundException`.
Return a 404 to the client as intended.

**Describe alternatives you've considered**

**Additional context**
```
nl-kat-coordination-katalogus-1  | [2023-12-11 10:13:41 +0000] [9] [ERROR] [db] An error occurred: eee. Rolling back session
nl-kat-coordination-katalogus-1  | boefjes.sql.db.ObjectNotFoundException: The object of type <class 'boefjes.sql.db_models.OrganisationInDB'> was not found for query parameters {'id': 'eee'}
nl-kat-coordination-katalogus-1  | 
nl-kat-coordination-katalogus-1  | The above exception was the direct cause of the following exception:
nl-kat-coordination-katalogus-1  | 
nl-kat-coordination-katalogus-1  | Traceback (most recent call last):
nl-kat-coordination-katalogus-1  |   File "/app/boefjes/boefjes/sql/db.py", line 34, in session_managed_iterator
nl-kat-coordination-katalogus-1  |     yield service
nl-kat-coordination-katalogus-1  | boefjes.katalogus.storage.interfaces.OrganisationNotFound: eee
nl-kat-coordination-katalogus-1  | [2023-12-11 10:13:41 +0000] [9] [INFO] [db] Closing session for <class 'boefjes.sql.organisation_storage.SQLOrganisationStorage'>
nl-kat-coordination-katalogus-1  | [2023-12-11 10:13:41 +0000] [9] [ERROR] [api] some error
nl-kat-coordination-katalogus-1  | boefjes.sql.db.ObjectNotFoundException: The object of type <class 'boefjes.sql.db_models.OrganisationInDB'> was not found for query parameters {'id': 'eee'}
nl-kat-coordination-katalogus-1  | 
nl-kat-coordination-katalogus-1  | The above exception was the direct cause of the following exception:
nl-kat-coordination-katalogus-1  | 
nl-kat-coordination-katalogus-1  | Traceback (most recent call last):
nl-kat-coordination-katalogus-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
nl-kat-coordination-katalogus-1  |     await self.app(scope, receive, sender)
nl-kat-coordination-katalogus-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
nl-kat-coordination-katalogus-1  |     raise e
nl-kat-coordination-katalogus-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
nl-kat-coordination-katalogus-1  |     await self.app(scope, receive, send)
nl-kat-coordination-katalogus-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
nl-kat-coordination-katalogus-1  |     await route.handle(scope, receive, send)
nl-kat-coordination-katalogus-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
nl-kat-coordination-katalogus-1  |     await self.app(scope, receive, send)
nl-kat-coordination-katalogus-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
nl-kat-coordination-katalogus-1  |     response = await func(request)
nl-kat-coordination-katalogus-1  |                ^^^^^^^^^^^^^^^^^^^
nl-kat-coordination-katalogus-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
nl-kat-coordination-katalogus-1  |     raw_response = await run_endpoint_function(
nl-kat-coordination-katalogus-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nl-kat-coordination-katalogus-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
nl-kat-coordination-katalogus-1  |     return await run_in_threadpool(dependant.call, **values)
nl-kat-coordination-katalogus-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nl-kat-coordination-katalogus-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
nl-kat-coordination-katalogus-1  |     return await anyio.to_thread.run_sync(func, *args)
nl-kat-coordination-katalogus-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nl-kat-coordination-katalogus-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 49, in run_sync
nl-kat-coordination-katalogus-1  |     return await get_async_backend().run_sync_in_worker_thread(
nl-kat-coordination-katalogus-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nl-kat-coordination-katalogus-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2103, in run_sync_in_worker_thread
nl-kat-coordination-katalogus-1  |     return await future
nl-kat-coordination-katalogus-1  |            ^^^^^^^^^^^^
nl-kat-coordination-katalogus-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 823, in run
nl-kat-coordination-katalogus-1  |     result = context.run(func, *args)
nl-kat-coordination-katalogus-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^
nl-kat-coordination-katalogus-1  |   File "/app/boefjes/boefjes/katalogus/routers/organisations.py", line 44, in get_organisation
nl-kat-coordination-katalogus-1  |     return storage.get_by_id(organisation_id)
nl-kat-coordination-katalogus-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nl-kat-coordination-katalogus-1  |   File "/app/boefjes/boefjes/sql/organisation_storage.py", line 27, in get_by_id
nl-kat-coordination-katalogus-1  |     instance = self._db_instance_by_id(organisation_id)
nl-kat-coordination-katalogus-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nl-kat-coordination-katalogus-1  |   File "/app/boefjes/boefjes/sql/organisation_storage.py", line 67, in _db_instance_by_id
nl-kat-coordination-katalogus-1  |     raise OrganisationNotFound(organisation_id) from ObjectNotFoundException(
nl-kat-coordination-katalogus-1  | boefjes.katalogus.storage.interfaces.OrganisationNotFound: eee

```

**Comment by Donnype** [comment]
For which API calls does this hold? I just added an integration test to check the behavior and found, at least for the organisation API, what we'd expect (i.e. this test passes):

![Image](https://github.com/user-attachments/assets/226b81f5-9226-4398-b056-2cf98a4f8631)
