### ISSUE TITLE
Starting a manual scan doesn't work

### ISSUE THREAD

**Issue by dekkers** [minvws/nl-kat-coordination#2161]
**Describe the bug**
Starting a manual scan on boefje detail page doesn't work.

**To Reproduce**
Go to boefje page, select OOIs and start scan.

**Expected behavior**
The boefje is successfully started.

**Logs**
```
boefje_1  | [2023-12-18 21:35:34 +0000] [1] [ERROR] [app] Popping task from scheduler failed, sleeping 10 seconds
boefje_1  | Traceback (most recent call last):
boefje_1  |   File "/app/boefjes/boefjes/app.py", line 105, in _fill_queue
boefje_1  |     p_item = self.scheduler_client.pop_item(queue_type.id)
boefje_1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
boefje_1  |   File "/app/boefjes/boefjes/clients/scheduler_client.py", line 104, in pop_item
boefje_1  |     return TypeAdapter(Optional[QueuePrioritizedItem]).validate_json(response.content)
boefje_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
boefje_1  |   File "/usr/local/lib/python3.11/site-packages/pydantic/type_adapter.py", line 256, in validate_json
boefje_1  |     return self.validator.validate_json(__data, strict=strict, context=context)
boefje_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
boefje_1  | pydantic_core._pydantic_core.ValidationError: 4 validation errors for nullable[QueuePrioritizedItem]
boefje_1  | data.BoefjeMeta.id
boefje_1  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
boefje_1  |     For further information visit https://errors.pydantic.dev/2.5/v/uuid_type
boefje_1  | data.NormalizerMeta.id
boefje_1  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
boefje_1  |     For further information visit https://errors.pydantic.dev/2.5/v/uuid_type
boefje_1  | data.NormalizerMeta.raw_data
boefje_1  |   Field required [type=missing, input_value={'id': None, 'boefje': {'... 'organization': 'test'}, input_type=dict]
boefje_1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
boefje_1  | data.NormalizerMeta.normalizer
boefje_1  |   Field required [type=missing, input_value={'id': None, 'boefje': {'... 'organization': 'test'}, input_type=dict]
boefje_1  |     For further information visit https://errors.pydantic.dev/2.5/v/missing
```

Task json downloaded from task page:
```
{
  "id": "f4dd73f4-a8d6-4a5c-8e89-19b80e1385f4",
  "scheduler_id": "boefje-test",
  "type": "boefje",
  "p_item": {
    "id": "f4dd73f4-a8d6-4a5c-8e89-19b80e1385f4",
    "hash": "800cd590c590315d40eb21e61665eb55",
    "priority": 1,
    "data": {
      "id": null,
      "boefje": {
        "id": "nmap",
        "name": "Nmap TCP",
        "version": null
      },
      "input_ooi": "IPAddressV6|internet|2a03:6000:1018::36",
      "organization": "test",
      "type": "boefje"
    }
  },
  "status": "dispatched",
  "created_at": "2023-12-18T21:34:09.877493Z",
  "modified_at": "2023-12-18T21:34:09.877499Z"
}
```

**OpenKAT version**
main

**Comment by jpbruinsslot** [comment]
Default value of a BoefjeTask id is set to None. This is allowed by the scheduler picking this up on https://github.com/minvws/nl-kat-coordination/issues/2167

I removed the id field from the BoefjeTask model within rocky, however this might not be desirable

**Comment by underdarknl** [comment]
I was able to start a scan on our current Main branch just fine. This from the object detail page's boefje list with no changes applied.
