### ISSUE TITLE
AttributeError: 'ForcedIPHTTPSConnectionPool' object has no attribute 'strict'

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#2405]
Was reproducing a bug, but the instead I ran into a problem with the WebpageAnalysis boefje task failed. Upon inspection it threw a python error as shown below. 

**To Reproduce**
1. Add URL object and set L2 clearance
2. Enable DNS boefjes and WebpageAnalysis boefje
3. Wait until task failed.

**Expected behavior**
The Webpageanalysis boefje should run without failing and it should result in analysis of headers and corresponding findings if available. 

**OpenKAT version**
commit fea21f9828cbecee4f6982494eba87422f104a7e (HEAD -> main, origin/main, origin/HEAD)

**Log files**
[attributeerror.tar.gz](https://github.com/minvws/nl-kat-coordination/files/14111743/attributeerror.tar.gz)

The contents of the RAW file: 

```
Traceback (most recent call last):
  File "/app/boefjes/boefjes/local.py", line 53, in run
    return boefje_resource.module.run(boefje_meta)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/boefjes/boefjes/plugins/kat_webpage_analysis/main.py", line 55, in run
    response = do_request(hostname, session, uri, useragent)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/boefjes/boefjes/plugins/kat_webpage_analysis/main.py", line 78, in do_request
    response = session.get(
               ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 769, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 295, in _get_conn
    return conn or self._new_conn()
                   ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/forcediphttpsadapter/adapters.py", line 141, in _new_conn
    strict=self.strict, **conn_kw)
           ^^^^^^^^^^^
AttributeError: 'ForcedIPHTTPSConnectionPool' object has no attribute 'strict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/boefjes/boefjes/job_handler.py", line 150, in handle
    boefje_results = self.job_runner.run(boefje_meta, boefje_meta.environment)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/boefjes/boefjes/local.py", line 55, in run
    raise JobRuntimeError("Boefje failed") from e
boefjes.runtime_interfaces.JobRuntimeError: Boefje failed
```

The corresponding .json file:

```
{"id": "8ae9ae1d-b3c1-49cd-aaeb-05bea5ac4745", "boefje_meta": {"id": "8387b847-63dd-40fe-a8d2-81b013ac6002", "started_at": "2024-01-31T11:56:03.807629Z", "ended_at": "2024-01-31T11:56:03.811981Z", "boefje": {"id": "webpage-analysis", "version": null}, "input_ooi": "HTTPResource|internet|145.97.37.81|tcp|443|https|internet|kennisnet.nl|https|internet|kennisnet.nl|443|/", "arguments": {"input": {"object_type": "HTTPResource", "scan_profile": "scan_profile_type='inherited' reference=Reference('HTTPResource|internet|145.97.37.81|tcp|443|https|internet|kennisnet.nl|https|internet|kennisnet.nl|443|/') level=<ScanLevel.L2: 2>", "primary_key": "HTTPResource|internet|145.97.37.81|tcp|443|https|internet|kennisnet.nl|https|internet|kennisnet.nl|443|/", "website": {"ip_service": {"ip_port": {"address": {"network": {"name": "internet"}, "address": "145.97.37.81"}, "protocol": "tcp", "port": "443"}, "service": {"name": "https"}}, "hostname": {"network": {"name": "internet"}, "name": "kennisnet.nl"}}, "web_url": {"scheme": "https", "netloc": {"network": {"name": "internet"}, "name": "kennisnet.nl"}, "port": "443", "path": "/"}, "redirects_to": "None"}}, "organization": "ee", "runnable_hash": "67fb91f7ab4e4423e717ff42c305234b53ae62db323cbc540a64d3f8828a42b9", "environment": {}}, "mime_types": [{"value": "boefje/webpage-analysis"}, {"value": "error/boefje"}], "secure_hash": "sha512:9eb93a9122726925388957ae40ba17bfde1e661c5903961b96b74e0af42fa933f556cab0e23f944af3c8647decf84e071ece9d642a9068de58e692faa7ea0aa5", "signing_provider_url": null, "hash_retrieval_link": "5345ef53-f1a2-46a1-9d47-84c490648e15"}
```

**Comment by underdarknl** [comment]
Maybe its related to this issue, and thus a verion specific bug introduced when we upgraded various packages recently?

https://github.com/Roadmaster/forcediphttpsadapter/issues/15
