### ISSUE TITLE
 Intro/onboarding returns 500 when setting clearance level

### ISSUE THREAD

**Issue by d3vzer0** [minvws/nl-kat-coordination#25]
### Describe the bug, issue or concern

When setting the clearance level during the onboarding/introduction Django returns a HTTP 500 error.

### To Reproduce
1. Follow the installation procedures to build the Docker images (and .env)
2. Run the environment using docker-compose up -d for the first time
3. Login and enroll for 2FA
4. Follow the onboarding procedures untill you reach the clearance level page @ http://localhost:8000/onboarding/step/set-clearance-level/?ooi_id=URL%7Cinternet%7Chttp%3A%2F%2Flocalhost 
5. Press '**Zet vrijwaringsniveau**'

### Expected behavior
Expected to continue to the next page of the onboarding

### Screenshots
![Screenshot 2022-07-28 at 13 56 34](https://user-images.githubusercontent.com/34250156/181499580-a5fa58b4-b99f-4e17-ab64-bc17747101ff.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 102.0.1 

#### Django traceback
```
Environment:


Request Method: GET
Request URL: http://localhost:8000/onboarding/step/setup-scan/select-plugins/?ooi_id=URL%7Cinternet%7Chttp%3A%2F%2Flocalhost

Django Version: 3.2.14
Python Version: 3.8.13
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.forms',
 'django_otp',
 'django_otp.plugins.otp_static',
 'django_otp.plugins.otp_totp',
 'markdownify.apps.MarkdownifyConfig',
 'two_factor',
 'tools',
 'fmea',
 'crisis_room',
 'onboarding',
 'django_password_validators',
 'django_password_validators.password_history']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django_otp.middleware.OTPMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'rocky.middleware.active_organization_middleware.ActiveOrganizationMiddleware',
 'rocky.middleware.active_organization_middleware.OctopoesConnectorMiddleware',
 'rocky.middleware.onboarding.OnboardingMiddleware']



Traceback (most recent call last):
  File "/home/rocky/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/rocky/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rocky/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rocky/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/rocky/.local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/rocky/.local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/rocky/.local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 128, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/rocky/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/rocky/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "/app/rocky/onboarding/views.py", line 153, in get_context_data
    context["checkbox_group_table_form"] = (self.get_form(),)
  File "/app/rocky/onboarding/views.py", line 114, in get_form
    boefjes = self.report.get_boefjes(self.request.active_organization)
  File "/app/rocky/rocky/views/ooi_report.py", line 223, in get_boefjes
    katalogus_boefjes = get_katalogus(organization.code).get_boefjes()
  File "/app/rocky/rocky/katalogus.py", line 71, in get_boefjes
    response.raise_for_status()
  File "/home/rocky/.local/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

Exception Type: HTTPError at /onboarding/step/setup-scan/select-plugins/
Exception Value: 500 Server Error: Internal Server Error for url: http://katalogus:8000/v1/organisations/_dev/plugins

```
### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by d3vzer0** [comment]
Seems to be related to the scheduler not being able to start properly 🤔 

```
[2022-07-28 12:02:57 +0000] [1] [DEBUG] [connectionpool] [urllib3.connectionpool] Retry: /v1/organisations
[2022-07-28 12:02:57 +0000] [1] [DEBUG] [connectionpool] [urllib3.connectionpool] Resetting dropped connection: katalogus
[2022-07-28 12:02:57 +0000] [1] [DEBUG] [connectionpool] [urllib3.connectionpool] http://katalogus:8000 "GET /v1/organisations HTTP/1.1" 500 21
[2022-07-28 12:02:57 +0000] [1] [DEBUG] [retry] [urllib3.util.retry] Incremented Retry for (url='/v1/organisations'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
[2022-07-28 12:02:59 +0000] [1] [DEBUG] [connectionpool] [urllib3.connectionpool] Retry: /v1/organisations
[2022-07-28 12:02:59 +0000] [1] [DEBUG] [connectionpool] [urllib3.connectionpool] Resetting dropped connection: katalogus
[2022-07-28 12:02:59 +0000] [1] [DEBUG] [connectionpool] [urllib3.connectionpool] http://katalogus:8000 "GET /v1/organisations HTTP/1.1" 500 21
Traceback (most recent call last):
  File "/home/scheduler/.local/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/scheduler/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/home/scheduler/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/home/scheduler/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/home/scheduler/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/home/scheduler/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/home/scheduler/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 868, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/home/scheduler/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='katalogus', port=8000): Max retries exceeded with url: /v1/organisations (Caused by ResponseError('too many 500 error responses'))
```

**Comment by d3vzer0** [comment]
Ran the installation again from scratch and seems to work now, not entirely sure what went wrong on the first try :) I'll see if I can find out what went wrong and re-open the issue if needed

**Comment by underdarknl** [comment]
Thanks for letting us know, we have been seeing a few rough edges around these parts, and would like to fix them. Getting info like this helps.
