### ISSUE TITLE
500 error: Scheduler exception with Octopoes

### ISSUE THREAD

**Issue by Rieven** [minvws/nl-kat-coordination#2768]
![image](https://github.com/minvws/nl-kat-coordination/assets/30832687/de1f1ea7-dc4f-43b3-8dfa-cd81280ef00e)

**Comment by jpbruinsslot** [comment]
Handling of the `NoneType` will be picked up by https://github.com/minvws/nl-kat-coordination/issues/2769 But that won't solve the problem that you're having with octopoes. What is the API output from Octopoes when you curl the HTTP Request that you see in your screenshot?

**Comment by Rieven** [comment]
> Handling of the `NoneType` will be picked up by #2769 But that won't solve the problem that you're having with octopoes. What is the response from Octopoes when you curl the HTTP Request that you see in your screenshot?

Traceback (most recent call last):
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
2024-04-03 12:12:04     result = await app(  # type: ignore[func-returns-value]
2024-04-03 12:12:04              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-04-03 12:12:04     return await self.app(scope, receive, send)
2024-04-03 12:12:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-04-03 12:12:04     await super().__call__(scope, receive, send)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-04-03 12:12:04     await self.middleware_stack(scope, receive, send)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-04-03 12:12:04     raise exc
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-04-03 12:12:04     await self.app(scope, receive, _send)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-04-03 12:12:04     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-04-03 12:12:04     raise exc
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-04-03 12:12:04     await app(scope, receive, sender)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
2024-04-03 12:12:04     await self.middleware_stack(scope, receive, send)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
2024-04-03 12:12:04     await route.handle(scope, receive, send)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
2024-04-03 12:12:04     await self.app(scope, receive, send)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
2024-04-03 12:12:04     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-04-03 12:12:04     raise exc
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-04-03 12:12:04     await app(scope, receive, sender)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
2024-04-03 12:12:04     response = await func(request)
2024-04-03 12:12:04                ^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
2024-04-03 12:12:04     raise e
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
2024-04-03 12:12:04     raw_response = await run_endpoint_function(
2024-04-03 12:12:04                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
2024-04-03 12:12:04     return await run_in_threadpool(dependant.call, **values)
2024-04-03 12:12:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
2024-04-03 12:12:04     return await anyio.to_thread.run_sync(func, *args)
2024-04-03 12:12:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-04-03 12:12:04     return await get_async_backend().run_sync_in_worker_thread(
2024-04-03 12:12:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
2024-04-03 12:12:04     return await future
2024-04-03 12:12:04            ^^^^^^^^^^^^
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
2024-04-03 12:12:04     result = context.run(func, *args)
2024-04-03 12:12:04              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/app/octopoes/octopoes/api/router.py", line 237, in list_random_objects
2024-04-03 12:12:04     return octopoes.list_random_ooi(valid_time, amount, scan_level)
2024-04-03 12:12:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/app/octopoes/octopoes/core/service.py", line 508, in list_random_ooi
2024-04-03 12:12:04     oois = self.ooi_repository.list_random(valid_time, amount, scan_levels)
2024-04-03 12:12:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/app/octopoes/octopoes/repositories/ooi_repository.py", line 355, in list_random
2024-04-03 12:12:04     res = self.session.client.query(query, valid_time)
2024-04-03 12:12:04           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/app/octopoes/octopoes/xtdb/client.py", line 127, in query
2024-04-03 12:12:04     self._verify_response(res)
2024-04-03 12:12:04   File "/app/octopoes/octopoes/xtdb/client.py", line 66, in _verify_response
2024-04-03 12:12:04     raise e
2024-04-03 12:12:04   File "/app/octopoes/octopoes/xtdb/client.py", line 60, in _verify_response
2024-04-03 12:12:04     response.raise_for_status()
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
2024-04-03 12:12:04     raise HTTPStatusError(message, request=request, response=self)
2024-04-03 12:12:04 httpx.HTTPStatusError: Client error '404 Not Found' for url 'http://crux:3000/_xtdb/_rieven/query?valid-time=2024-04-03T10%3A12%3A04.414762%2B00%3A00'
2024-04-03 12:12:04 For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
2024-04-03 12:12:04 [2024-04-03 10:12:04 +0000] [8] [INFO] [h11_impl] 172.30.0.12:35478 - "GET /rieven/objects/random?amount=50&scan_level=1&scan_level=2&scan_level=3&scan_level=4&valid_time=2024-04-03%2010%3A12%3A04.409872%2B00%3A00 HTTP/1.1" 200
2024-04-03 12:12:04 [2024-04-03 10:12:04 +0000] [8] [INFO] [h11_impl] 172.30.0.12:35478 - "GET /rieven/objects?types=ADRFindingType&scan_level=0&scan_level=1&scan_level=2&scan_level=3&scan_level=4&offset=0&limit=1&valid_time=2024-04-03%2010%3A12%3A04.894762%2B00%3A00 HTTP/1.1" 200
2024-04-03 12:12:04 [2024-04-03 10:12:04 +0000] [8] [INFO] [h11_impl] 172.30.0.12:35478 - "GET /rieven/objects?types=CVEFindingType&scan_level=0&scan_level=1&scan_level=2&scan_level=3&scan_level=4&offset=0&limit=1&valid_time=2024-04-03%2010%3A12%3A04.906927%2B00%3A00 HTTP/1.1" 200
2024-04-03 12:12:04 [2024-04-03 10:12:04 +0000] [8] [CRITICAL] [api] Client error '404 Not Found' for url 'http://crux:3000/_xtdb/_rieven/query?valid-time=2024-04-03T10%3A12%3A04.931600%2B00%3A00'
2024-04-03 12:12:04 For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
2024-04-03 12:12:04 [2024-04-03 10:12:04 +0000] [8] [INFO] [h11_impl] 172.30.0.12:35500 - "GET /_rieven/objects?types=ADRFindingType&scan_level=0&scan_level=1&scan_level=2&scan_level=3&scan_level=4&offset=0&limit=1&valid_time=2024-04-03%2010%3A12%3A04.931600%2B00%3A00 HTTP/1.1" 500
2024-04-03 12:12:04 [2024-04-03 10:12:04 +0000] [8] [ERROR] [h11_impl] Exception in ASGI application
2024-04-03 12:12:04 Traceback (most recent call last):
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
2024-04-03 12:12:04     result = await app(  # type: ignore[func-returns-value]
2024-04-03 12:12:04              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-04-03 12:12:04     return await self.app(scope, receive, send)
2024-04-03 12:12:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-04-03 12:12:04     await super().__call__(scope, receive, send)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-04-03 12:12:04     await self.middleware_stack(scope, receive, send)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-04-03 12:12:04     raise exc
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-04-03 12:12:04     await self.app(scope, receive, _send)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-04-03 12:12:04     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-04-03 12:12:04     raise exc
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-04-03 12:12:04     await app(scope, receive, sender)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
2024-04-03 12:12:04     await self.middleware_stack(scope, receive, send)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
2024-04-03 12:12:04     await route.handle(scope, receive, send)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
2024-04-03 12:12:04     await self.app(scope, receive, send)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
2024-04-03 12:12:04     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-04-03 12:12:04     raise exc
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-04-03 12:12:04     await app(scope, receive, sender)
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
2024-04-03 12:12:04     response = await func(request)
2024-04-03 12:12:04                ^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
2024-04-03 12:12:04     raise e
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
2024-04-03 12:12:04     raw_response = await run_endpoint_function(
2024-04-03 12:12:04                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
2024-04-03 12:12:04     return await run_in_threadpool(dependant.call, **values)
2024-04-03 12:12:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
2024-04-03 12:12:04     return await anyio.to_thread.run_sync(func, *args)
2024-04-03 12:12:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-04-03 12:12:04     return await get_async_backend().run_sync_in_worker_thread(
2024-04-03 12:12:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
2024-04-03 12:12:04     return await future
2024-04-03 12:12:04            ^^^^^^^^^^^^
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
2024-04-03 12:12:04     result = context.run(func, *args)
2024-04-03 12:12:04              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/app/octopoes/octopoes/api/router.py", line 123, in list_objects
2024-04-03 12:12:04     return octopoes.list_ooi(types, valid_time, offset, limit, scan_level, scan_profile_type)
2024-04-03 12:12:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/app/octopoes/octopoes/core/service.py", line 129, in list_ooi
2024-04-03 12:12:04     paginated = self.ooi_repository.list_oois(types, valid_time, limit, offset, scan_levels, scan_profile_types)
2024-04-03 12:12:04                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/app/octopoes/octopoes/repositories/ooi_repository.py", line 299, in list_oois
2024-04-03 12:12:04     res_count = self.session.client.query(count_query, valid_time)
2024-04-03 12:12:04                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-03 12:12:04   File "/app/octopoes/octopoes/xtdb/client.py", line 127, in query
2024-04-03 12:12:04     self._verify_response(res)
2024-04-03 12:12:04   File "/app/octopoes/octopoes/xtdb/client.py", line 66, in _verify_response
2024-04-03 12:12:04     raise e
2024-04-03 12:12:04   File "/app/octopoes/octopoes/xtdb/client.py", line 60, in _verify_response
2024-04-03 12:12:04     response.raise_for_status()
2024-04-03 12:12:04   File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
2024-04-03 12:12:04     raise HTTPStatusError(message, request=request, response=self)
2024-04-03 12:12:04 httpx.HTTPStatusError: Client error '404 Not Found' for url 'http://crux:3000/_xtdb/_rieven/query?valid-time=2024-04-03T10%3A12%3A04.931600%2B00%3A00'

**Comment by originalsouth** [comment]
@Rieven can you provide a minimal way to reproduce this?

**Comment by Rieven** [comment]
`2024-04-17 15:04:08 WARNING:root:Deprecation: SCHEDULER_DB_DSN is deprecated, use SCHEDULER_DB_URI instead
2024-04-17 15:04:10   File "/app/scheduler/scheduler/schedulers/boefje.py", line 285, in push_tasks_for_random_objects
2024-04-17 15:04:10     random_oois = self.ctx.services.octopoes.get_random_objects(
2024-04-17 15:04:10                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-17 15:04:10   File "/app/scheduler/scheduler/connectors/errors.py", line 14, in inner_function
2024-04-17 15:04:10     return func(*args, **kwargs)
2024-04-17 15:04:10            ^^^^^^^^^^^^^^^^^^^^^
2024-04-17 15:04:10   File "/app/scheduler/scheduler/connectors/services/octopoes.py", line 77, in get_random_objects
2024-04-17 15:04:10     return [OOI(**ooi) for ooi in response.json()]
2024-04-17 15:04:10            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-17 15:04:10   File "/app/scheduler/scheduler/connectors/services/octopoes.py", line 77, in <listcomp>
2024-04-17 15:04:10     return [OOI(**ooi) for ooi in response.json()]
2024-04-17 15:04:10             ^^^^^^^^^^
2024-04-17 15:04:10 TypeError: scheduler.models.ooi.OOI() argument after ** must be a mapping, not str
2024-04-17 15:04:10 Traceback (most recent call last):
2024-04-17 15:04:10   File "/app/scheduler/scheduler/utils/thread.py", line 67, in run_forever
2024-04-17 15:04:10     self._target()
2024-04-17 15:04:10   File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
2024-04-17 15:04:10     return func(*args, **kwds)
2024-04-17 15:04:10            ^^^^^^^^^^^^^^^^^^^
2024-04-17 15:04:10   File "/app/scheduler/scheduler/schedulers/boefje.py", line 285, in push_tasks_for_random_objects
2024-04-17 15:04:10     random_oois = self.ctx.services.octopoes.get_random_objects(
2024-04-17 15:04:10                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-17 15:04:10   File "/app/scheduler/scheduler/connectors/errors.py", line 14, in inner_function
2024-04-17 15:04:10     return func(*args, **kwargs)
2024-04-17 15:04:10            ^^^^^^^^^^^^^^^^^^^^^
2024-04-17 15:04:10   File "/app/scheduler/scheduler/connectors/services/octopoes.py", line 77, in get_random_objects
2024-04-17 15:04:10     return [OOI(**ooi) for ooi in response.json()]
2024-04-17 15:04:10            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-17 15:04:10   File "/app/scheduler/scheduler/connectors/services/octopoes.py", line 77, in <listcomp>
2024-04-17 15:04:10     return [OOI(**ooi) for ooi in response.json()]
2024-04-17 15:04:10             ^^^^^^^^^^
2024-04-17 15:04:10 TypeError: scheduler.models.ooi.OOI() argument after ** must be a mapping, not str
2024-04-17 15:04:10 2024-04-17 13:04:10 [error    ] Unhandled exception occurred: scheduler.models.ooi.OOI() argument after ** must be a mapping, not str
2024-04-17 15:04:10 2024-04-17 13:04:10 [info     ] Shutdown initiated            
2024-04-17 15:04:10 2024-04-17 13:04:10 [info     ] Stopping scheduler: boefje-_rieven scheduler_id=boefje-_rieven`

**Comment by originalsouth** [comment]
```
2024-04-18 13:40:07 [info     ] Normalizer scheduler started for _rieven item_type=NormalizerTask organisation_id=_rieven scheduler_id=normalizer-_rieven
HTTP Request: GET http://octopoes_api/_rieven/objects/random?amount=50&scan_level=1&scan_level=2&scan_level=3&scan_level=4&valid_time=2024-04-18%2013%3A40%3A07.678771%2B00%3A00 "HTTP/1.1 400 Bad Request"
HTTP Request: GET http://katalogus:8000/v1/organisations "HTTP/1.1 200 OK"
2024-04-18 13:40:07 [exception] Exception in thread: BoefjeScheduler-boefje-_rieven-random
Traceback (most recent call last):
  File "/app/scheduler/scheduler/utils/thread.py", line 67, in run_forever
    self._target()
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/scheduler/scheduler/schedulers/boefje.py", line 285, in push_tasks_for_random_objects
    random_oois = self.ctx.services.octopoes.get_random_objects(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/scheduler/scheduler/connectors/errors.py", line 14, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/scheduler/scheduler/connectors/services/octopoes.py", line 77, in get_random_objects
    return [OOI(**ooi) for ooi in response.json()]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/scheduler/scheduler/connectors/services/octopoes.py", line 77, in <listcomp>
    return [OOI(**ooi) for ooi in response.json()]
            ^^^^^^^^^^
TypeError: scheduler.models.ooi.OOI() argument after ** must be a mapping, not str
Traceback (most recent call last):
  File "/app/scheduler/scheduler/utils/thread.py", line 67, in run_forever
    self._target()
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/scheduler/scheduler/schedulers/boefje.py", line 285, in push_tasks_for_random_objects
    random_oois = self.ctx.services.octopoes.get_random_objects(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/scheduler/scheduler/connectors/errors.py", line 14, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/scheduler/scheduler/connectors/services/octopoes.py", line 77, in get_random_objects
    return [OOI(**ooi) for ooi in response.json()]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/scheduler/scheduler/connectors/services/octopoes.py", line 77, in <listcomp>
    return [OOI(**ooi) for ooi in response.json()]
            ^^^^^^^^^^
TypeError: scheduler.models.ooi.OOI() argument after ** must be a mapping, not str
2024-04-18 13:40:07 [error    ] Unhandled exception occurred: scheduler.models.ooi.OOI() argument after ** must be a mapping, not str
2024-04-18 13:40:07 [info     ] Shutdown initiated
```

Where `GET http://octopoes_api/_rieven/objects/random?amount=50&scan_level=1&scan_level=2&scan_level=3&scan_level=4&valid_time=2024-04-18%2013%3A40%3A07.678771%2B00%3A00 "HTTP/1.1 400 Bad Request"` return a 400: `{"detail":"Type not found"}`, instead of an array/list object. 

So this is where https://github.com/minvws/nl-kat-coordination/blob/7b55b1a1b503a5d7e3d854264b96bb80888c8d97/mula/scheduler/connectors/services/octopoes.py#L62-L77 crashes.

**Comment by originalsouth** [comment]
Perhaps related to #258.
