### ISSUE TITLE
RAW files cannot be downloaded from Tasks page

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#2864]
**Describe the bug**
Under certain circumstances RAW files cannot be downloaded from the interface in the Tasks page. When filtering for 'failed' tasks and then clicking the 'Download meta and raw data' button results in a Javascript notification saying "Error: Getting raw data failed.". The bug seems to be related to something going wrong when parsing of some objects. Based on the logs and the tasks page this seems to happen for the following objects as minimum: IPService, HTTPResource and Website objects.  

The following boefjes were enabled that show as failed tasks. Please note that this doesn't seem to occur every single time, other tasks for these boefjes do seem to complete.: 
- testssl.sh
- WebpageAnalysis
- SSLCertificates
- Security.txt
- SSLScan

**To Reproduce**
1. Add a whole bunch of hostnames, though maybe with a single hostname you might see this too. Otherwise ping me for a hostname.
2. Enable the boefjes listed above (including Nmap TCP, though it doesn't throw an error at this time)
3. Check for failed tasks
4. Download the raw data for a failed task. You should see the error message. 

**Expected behavior**
Downloading the raw files for the task should be possible at all times, even if the task failed. In those cases the raw files should show the error for convenience for the user. 

**OpenKAT version**
Current main: commit 5aa3902ba9aa89f38ac2d3dae022322cdf208b24 (HEAD -> main, origin/main, origin/HEAD)

```
boefje-1  | [2024-04-18 07:34:40 +0000] [16] [INFO] [_client] HTTP Request: GET http://octopoes_api/ee/object?reference=IPService%7Cinternet%7C134.X.X.X%7Ctcp%7C53%7Cdomain&valid_time=2024-04-18%2007%3A34%3A40.042474%2B00%3A00 "HTTP/1.1 404 Not Found"
boefje-1  | [2024-04-18 07:34:40 +0000] [16] [ERROR] [app] An error occurred handling scheduler item[id=d3c259fa-7d3a-4cba-bde6-7ade89cd241f]
boefje-1  | Traceback (most recent call last):
boefje-1  |   File "/app/boefjes/octopoes/connector/octopoes.py", line 47, in _verify_response
boefje-1  |     response.raise_for_status()
boefje-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
boefje-1  |     raise HTTPStatusError(message, request=request, response=self)
boefje-1  | httpx.HTTPStatusError: Client error '404 Not Found' for url 'http://octopoes_api/ee/object?reference=IPService%7Cinternet%7C134.X.X.X%7Ctcp%7C53%7Cdomain&valid_time=2024-04-18%2007%3A34%3A40.042474%2B00%3A00'
boefje-1  | For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
boefje-1  | 
boefje-1  | During handling of the above exception, another exception occurred:
boefje-1  | 
boefje-1  | Traceback (most recent call last):
boefje-1  |   File "/app/boefjes/boefjes/job_handler.py", line 123, in handle
boefje-1  |     ooi = get_octopoes_api_connector(boefje_meta.organization).get(
boefje-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
boefje-1  |   File "/app/boefjes/octopoes/connector/octopoes.py", line 86, in get
boefje-1  |     res = self.session.get(
boefje-1  |           ^^^^^^^^^^^^^^^^^
boefje-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1054, in get
boefje-1  |     return self.request(
boefje-1  |            ^^^^^^^^^^^^^
boefje-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 827, in request
boefje-1  |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
boefje-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
boefje-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
boefje-1  |     response = self._send_handling_auth(
boefje-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
boefje-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
boefje-1  |     response = self._send_handling_redirects(
boefje-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
boefje-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 999, in _send_handling_redirects
boefje-1  |     raise exc
boefje-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 982, in _send_handling_redirects
boefje-1  |     hook(response)
boefje-1  |   File "/app/boefjes/octopoes/connector/octopoes.py", line 51, in _verify_response
boefje-1  |     raise ObjectNotFoundException(data["detail"])
boefje-1  | octopoes.models.exception.ObjectNotFoundException: IPService|internet|134.X.X.X|tcp|53|domain
boefje-1  | 
boefje-1  | The above exception was the direct cause of the following exception:
boefje-1  | 
boefje-1  | Traceback (most recent call last):
boefje-1  |   File "/app/boefjes/boefjes/app.py", line 247, in _start_working
boefje-1  |     handler.handle(p_item.data)
boefje-1  |   File "/app/boefjes/boefjes/job_handler.py", line 127, in handle
boefje-1  |     raise ObjectNotFoundException(f"Object {reference} not found in Octopoes") from e
boefje-1  | octopoes.models.exception.ObjectNotFoundException: Object IPService|internet|134.X.X.X|tcp|53|domain not found in Octopoes
```

**Comment by underdarknl** [comment]
It looks like the Input OOI related to the requested Raw file does not exists (anymore, or at that timestamp), possibly because there's a race condition somewhere that looks at the raw file's create-date, and not the OOI's create-date?
