### ISSUE TITLE
ValueError for adding AS object

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#2902]
**Describe the bug**
When trying to add an AutonomousSystem number as an object a ValueError is triggered. 

**To Reproduce**
1. Go to Objects
2. Add object 'Autonomous System'
3. Enter a value.

**Expected behavior**
Successful adding of an AS number. 

**Screenshots**

![image](https://github.com/minvws/nl-kat-coordination/assets/9821756/b1ce8198-9c6d-4122-a203-9d68ad0cac29)

**OpenKAT version**
commit 3588c77f085b5643823477b1636ed33a37d92302 (HEAD -> main, origin/main, origin/HEAD)

**StackTrace**
```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/en/aa/objects/add/AutonomousSystem/

Django Version: 4.2.11
Python Version: 3.11.9
Installed Applications:
['whitenoise.runserver_nostatic',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.forms',
 'django_otp',
 'django_otp.plugins.otp_static',
 'django_otp.plugins.otp_totp',
 'two_factor',
 'account',
 'tools',
 'fmea',
 'crisis_room',
 'onboarding',
 'katalogus',
 'django_password_validators',
 'django_password_validators.password_history',
 'rest_framework',
 'tagulous',
 'compressor',
 'reports',
 'knox',
 'csp']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django_otp.middleware.OTPMiddleware',
 'rocky.middleware.auth_required.AuthRequiredMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'rocky.middleware.onboarding.OnboardingMiddleware',
 'csp.middleware.CSPMiddleware']



Traceback (most recent call last):
  File "/app/rocky/rocky/views/ooi_view.py", line 168, in form_valid
    new_ooi = self.ooi_class.parse_obj(form.cleaned_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 1118, in parse_obj
    return cls.model_validate(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 551, in model_validate
    return cls.__pydantic_validator__.validate_python(
           

During handling of the above exception (1 validation error for AutonomousSystem
name
  Field required [type=missing, input_value={'number': 'aeua213'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing), another exception occurred:
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/rocky/rocky/views/ooi_view.py", line 174, in form_valid
    form.add_error(error["loc"][0], error["msg"])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 400, in add_error
    raise ValueError(
    ^

Exception Type: ValueError at /en/aa/objects/add/AutonomousSystem/
Exception Value: 'OOIForm' has no field named 'name'.
```

**Comment by stephanie0x00** [comment]
Grouped together into #2901
