### ISSUE TITLE
Missing staticfiles 

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#2973]
**Describe the bug**
When setting `DEBUG=False` in the .env file, the OpenKAT install crashes on a ValueError as shown below. This value error makes it not possible to load the KAT UIt. When setting `DEBUG=True` this ValueError is 'ignored' and it is possible to load the KAT UI. 

**To Reproduce**

1. Set `DEBUG=False` in .env.
2. make reset
3. Browse to http://127.0.0.1:8000/
4. See error in rocky-logs

**Expected behavior**
When having DEBUG mode disabled the UI should load. 

**Screenshots**
![image](https://github.com/minvws/nl-kat-coordination/assets/9821756/b4892f46-bfcc-48c8-a88b-1b9de6b82c66)

**OpenKAT version**
commit 951a52999e6905faf47427618d9afb5db9191426 (HEAD -> main, origin/main, origin/HEAD)

```
rocky-1  | Internal Server Error: /en/login/
rocky-1  | Traceback (most recent call last):
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
rocky-1  |     response = get_response(request)
rocky-1  |                ^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
rocky-1  |     response = response.render()
rocky-1  |                ^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/response.py", line 114, in render
rocky-1  |     self.content = self.rendered_content
rocky-1  |                    ^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
rocky-1  |     return template.render(context, self._request)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
rocky-1  |     return self.template.render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 175, in render
rocky-1  |     return self._render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
rocky-1  |     return self.nodelist.render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
rocky-1  |     return SafeString("".join([node.render_annotated(context) for node in self]))
rocky-1  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
rocky-1  |     return SafeString("".join([node.render_annotated(context) for node in self]))
rocky-1  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
rocky-1  |     return self.render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
rocky-1  |     return compiled_parent._render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
rocky-1  |     return self.nodelist.render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
rocky-1  |     return SafeString("".join([node.render_annotated(context) for node in self]))
rocky-1  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
rocky-1  |     return SafeString("".join([node.render_annotated(context) for node in self]))
rocky-1  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
rocky-1  |     return self.render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
rocky-1  |     return compiled_parent._render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
rocky-1  |     return self.nodelist.render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
rocky-1  |     return SafeString("".join([node.render_annotated(context) for node in self]))
rocky-1  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
rocky-1  |     return SafeString("".join([node.render_annotated(context) for node in self]))
rocky-1  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
rocky-1  |     return self.render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
rocky-1  |     return compiled_parent._render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
rocky-1  |     return self.nodelist.render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
rocky-1  |     return SafeString("".join([node.render_annotated(context) for node in self]))
rocky-1  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
rocky-1  |     return SafeString("".join([node.render_annotated(context) for node in self]))
rocky-1  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
rocky-1  |     return self.render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
rocky-1  |     result = block.nodelist.render(context)
rocky-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
rocky-1  |     return SafeString("".join([node.render_annotated(context) for node in self]))
rocky-1  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
rocky-1  |     return SafeString("".join([node.render_annotated(context) for node in self]))
rocky-1  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
rocky-1  |     return self.render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/loader_tags.py", line 208, in render
rocky-1  |     return template.render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 177, in render
rocky-1  |     return self._render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
rocky-1  |     return self.nodelist.render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
rocky-1  |     return SafeString("".join([node.render_annotated(context) for node in self]))
rocky-1  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
rocky-1  |     return SafeString("".join([node.render_annotated(context) for node in self]))
rocky-1  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
rocky-1  |     return self.render(context)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/templatetags/static.py", line 116, in render
rocky-1  |     url = self.url(context)
rocky-1  |           ^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/templatetags/static.py", line 113, in url
rocky-1  |     return self.handle_simple(path)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/templatetags/static.py", line 129, in handle_simple
rocky-1  |     return staticfiles_storage.url(path)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/app/rocky/rocky/storage.py", line 16, in url
rocky-1  |     return super().url(name, force)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 203, in url
rocky-1  |     return self._url(self.stored_name, name, force)
rocky-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 182, in _url
rocky-1  |     hashed_name = hashed_name_func(*args)
rocky-1  |                   ^^^^^^^^^^^^^^^^^^^^^^^
rocky-1  |   File "/usr/local/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 513, in stored_name
rocky-1  |     raise ValueError(
rocky-1  | ValueError: Missing staticfiles manifest entry for 'img/favicon.svg'
rocky-1  | [21/May/2024 07:57:28] "GET /en/login/?next=/favicon.ico HTTP/1.1" 500 145

```

**Comment by deviserops** [comment]
Hi @stephanie0x00 

I think that is does not find any file at your provided static path.
Since you did not share your config for static file in settings.py you can try with this sample.

It will check if debug is true or false since env only provide string output you need to make sure you check boolean from env as a string and check if debug is on or off.

```python
DEBUG = os.getenv('DEBUG') != 'False'


if DEBUG:
    STATICFILES_DIRS = [
        Path.joinpath(BASE_DIR, 'static')
    ]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = os.getenv('STATIC_URL') if os.getenv('STATIC_URL') else 'static/'

MEDIA_ROOT = Path.joinpath(BASE_DIR, 'media')
MEDIA_URL = 'media/'

```

**Comment by underdarknl** [comment]
The issue mentioned here is due to the fact the redirect url for favicon.ico does not exist and cannot be constructed. However, there seems to be a general 500 error when setting debug to False unrelated to the favicon path.

N.B. The favicon url seems to be redirected to the login screen due to only 'allowed / safe' urls being visible for guest users.
