### ISSUE TITLE
UnknownHeaderField

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3094]
**Describe the bug**
When performing a DNS check against mispo.es (such as the onboarding), one of the normalizers (kat_dns_normalize) fails against one of the nameservers. The error and log files can be found below. 

**To Reproduce**

1. Do the onboarding with https://mispo.es.
2. After completion check for failed tasks and observe that one of the normalizers failed.
3. See error

**Expected behavior**
The normalizer parser doesn't fail when parsing DNS output. 

**OpenKAT version**
commit 24d01b4b8661e01f4bc8ce96ec9a5a63b215c56e (HEAD -> main, origin/main, origin/HEAD)

**Errors & logs**
- The error message shown in the docker logs is shown below. 
```
normalizer-1  | [2024-06-17 12:17:43 +0000] [15] [ERROR] [app] An error occurred handling scheduler item[id=8cc238a5-8eac-45a7-9b76-4be082e99a43]
normalizer-1  | Traceback (most recent call last):
normalizer-1  |   File "/app/boefjes/boefjes/app.py", line 247, in _start_working
normalizer-1  |     handler.handle(p_item.data)
normalizer-1  |   File "/app/boefjes/boefjes/job_handler.py", line 196, in handle
normalizer-1  |     results = self.job_runner.run(normalizer_meta, raw)
normalizer-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
normalizer-1  |   File "/app/boefjes/boefjes/local.py", line 85, in run
normalizer-1  |     return self._parse_results(normalizer_meta, results)
normalizer-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
normalizer-1  |   File "/app/boefjes/boefjes/local.py", line 93, in _parse_results
normalizer-1  |     for result in results:
normalizer-1  |   File "/app/boefjes/boefjes/plugins/kat_dns/normalize.py", line 49, in run
normalizer-1  |     responses.append(from_text("\n".join(lines[1:])))
normalizer-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
normalizer-1  |   File "/usr/local/lib/python3.11/site-packages/dns/message.py", line 1678, in from_text
normalizer-1  |     return reader.read()
normalizer-1  |            ^^^^^^^^^^^^^
normalizer-1  |   File "/usr/local/lib/python3.11/site-packages/dns/message.py", line 1627, in read
normalizer-1  |     line_method(section_number)
normalizer-1  |   File "/usr/local/lib/python3.11/site-packages/dns/message.py", line 1462, in _header_line
normalizer-1  |     raise UnknownHeaderField
normalizer-1  | dns.message.UnknownHeaderField: The header field name was not recognized when converting from text
normalizer-1  |     into a message.
```

- The output of the raw files of this task are:

```
{"dns_records": "RESOLVER: 1.1.1.1\nid 22260\nopcode QUERY\nrcode NOERROR\nflags QR RD RA\nedns 0\npayload 1232\noption EDE 10 (Rrsigs Missing): for DNSKEY be., id = 12664\n;QUESTION\nopenprovider.be. IN SOA\n;ANSWER\nopenprovider.be. 900 IN SOA ns-eu-west-2.openprovider.eu. sre.openprovider.nl. 2022122002 3600 600 604800 600\n;AUTHORITY\n;ADDITIONAL\n\nRESOLVER: 1.1.1.1\nid 64579\nopcode QUERY\nrcode NOERROR\nflags QR RD RA\nedns 0\npayload 1232\noption EDE 10 (Rrsigs Missing): for DNSKEY be., id = 12664\n;QUESTION\nns2.openprovider.be. IN A\n;ANSWER\nns2.openprovider.be. 164 IN A 162.159.27.96\n;AUTHORITY\n;ADDITIONAL\n\nRESOLVER: 1.1.1.1\nid 50715\nopcode QUERY\nrcode NOERROR\nflags QR RD RA\nedns 0\npayload 1232\noption EDE 10 (Rrsigs Missing): for DNSKEY be., id = 12664\n;QUESTION\nns2.openprovider.be. IN AAAA\n;ANSWER\nns2.openprovider.be. 444 IN AAAA 2400:cb00:2049:1::a29f:1b60\n;AUTHORITY\n;ADDITIONAL", "dmarc_response": "NXDOMAIN", "dkim_response": "NXDOMAIN"
```

and: 

```
{"id": "b30ba77a-fe1a-4b3f-8101-582abf6d6cc1", "boefje_meta": {"id": "1e0f0afd-f49e-4cfb-a102-c34a96098588", "started_at": "2024-06-17T12:17:38.282067Z", "ended_at": "2024-06-17T12:17:38.729783Z", "boefje": {"id": "dns-records", "version": null}, "input_ooi": "Hostname|internet|ns2.openprovider.be", "arguments": {"input": {"object_type": "Hostname", "scan_profile": "scan_profile_type='inherited' reference=Reference('Hostname|internet|ns2.openprovider.be') level=<ScanLevel.L1: 1>", "primary_key": "Hostname|internet|ns2.openprovider.be", "network": {"name": "internet"}, "name": "ns2.openprovider.be", "dns_zone": "None", "registered_domain": "None"}}, "organization": "aa", "runnable_hash": "8ee3ac0f61ef17c8997deda94cd0ed145a0dbdd15ffc26d857e1c606f5365b86", "environment": {}}, "mime_types": [{"value": "boefje/dns-records"}], "secure_hash": "sha512:601254c0bea38144cbf951218c7b476727b00f2130d55be65ea6ada33965b725bb1634413b0e9bc0e72d252fc5d3a171acebada02fabedfc2678d0467cea5bd4", "signing_provider_url": null, "hash_retrieval_link": "436f148f-a5ea-4f9e-9b5c-bc435ab5de68"}
```

**Comment by underdarknl** [comment]
I think this is a duplicate of: https://github.com/minvws/nl-kat-coordination/issues/2805

**Comment by brennodewinter** [comment]
Consolidated into #2805 during backlog triage. The relevant scope and any unique context have been summarized on #2805. Closing this issue as a duplicate.
