### ISSUE TITLE
Snyk returns CVE findings with empty id

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3139]
The CVE Finding Type normalizer fails. 

**Steps to reproduce:**
- Enable DNS boefjes from the onboarding
- Enable nmap tcp, Webpage analysis and Snyk.io.
- Run on L2 clearance.
- Check for the failed normalizer task on the Tasks page. 

```
normalizer-1  | [2024-06-25 06:40:30 +0000] [16] [INFO] [job_handler] Handling normalizer kat_dns_norma
lize[fcfb5ec4-40c3-4900-be9c-8f2fd0ed278e]
normalizer-1  | [2024-06-25 06:40:30 +0000] [15] [ERROR] [app] An error occurred handling scheduler item[id=f8054f50-7fdb-4db8-8aab-04d057c30427]
normalizer-1  | Traceback (most recent call last):
normalizer-1  |   File "/app/boefjes/boefjes/app.py", line 247, in _start_working
normalizer-1  |     handler.handle(p_item.data)
normalizer-1  |   File "/app/boefjes/boefjes/job_handler.py", line 196, in handle
normalizer-1  |     results = self.job_runner.run(normalizer_meta, raw)
normalizer-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
normalizer-1  |   File "/app/boefjes/boefjes/local.py", line 85, in run
normalizer-1  |     return self._parse_results(normalizer_meta, results)
normalizer-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
normalizer-1  |   File "/app/boefjes/boefjes/local.py", line 93, in _parse_results
normalizer-1  |     for result in results:
normalizer-1  |   File "/app/boefjes/boefjes/plugins/kat_cve_finding_types/normalize.py", line 29, in run
normalizer-1  |     data = json.loads(raw)
normalizer-1  |            ^^^^^^^^^^^^^^^
normalizer-1  |   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
normalizer-1  |     return _default_decoder.decode(s)
normalizer-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
normalizer-1  |   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
normalizer-1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
normalizer-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
normalizer-1  |   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
normalizer-1  |     raise JSONDecodeError("Expecting value", s, err.value) from None
normalizer-1  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
normalizer-1  | [2024-06-25 06:40:30 +0000] [16] [INFO] [_client] HTTP Request: GET http://bytes:8000/bytes/raw/dabebf27-5a46-4dc0-bf32-6f5d16d84247 "HTTP/1.1 200 OK"

```

**Comment by underdarknl** [comment]
It looks like our handling of Snyk is correct, however not all listed Snyk findings  are backed by a detail page. This means we see various 404's returned by SNYK which in turn mean our Snyk Findings Hydration Boefje throw an error on these. I suspect these are no longer accessible due to archiving or license requirements.
I'd be ideal if we could use the snyk api in those cases where a user has supplied a snyk api-key. Optionally we could still use this non-api variant for those users who dont have an api-key

**Comment by stephanie0x00** [comment]
Created a new ticket for that issue, as the fix from @dekkers fixes the initial normalizer issue and this requires more work and possibly a discussion.
