### ISSUE TITLE
KAT intro crash

### ISSUE THREAD

**Issue by VincentZCERT** [minvws/nl-kat-coordination#32]
### Describe the bug, issue or concern

Na het installeren beginnen we bij de KAT introduction. Terwijl we deze doorlopen komen we bij de laatste stap "Open report". De DNS-scan wordt uitgevoerd en zodra de button "Open my DNS-report" oplicht, zou het report beschikbaar moeten zijn. Als je op de button klikt crasht het systeem.

![Bugreport 1 KAT](https://user-images.githubusercontent.com/96521120/186620819-1940be76-adb5-4990-beeb-3b8e03c4df05.PNG)

**Comment by underdarknl** [comment]
Vincent, Dat is niet de bedoeling, en onverwacht. @noamblitz kun jij Vincent verder helpen?

**Comment by noamblitz** [comment]
Ik heb mijn vermoedens, vooral dat de boefjes container niet draait mogelijk.

Voor iets meer context, zou je me de logs kunnen sturen van de octopoes_api container? 

Draai je dit toevallig op een ander OS dan linux?

**Comment by VincentZCERT** [comment]
Hi,

Ik draai het gewoon lokaal op een ubuntu-VM.
De logs zijn door mij en mijn collega’s niet zo te vinden (locatie onbekend) en onze devopser is momenteel druk met installatie van de container versie op onze omgeving.
Mvrgr,

Vincent Banse
Senior Security Specialist Z-CERT
+31 (0)6 12906351

Z-CERT
Sectorale CERT voor de zorg
Stationsplein 121 | 3818 LE | Amersfoort
T +31 (0)33 737 0609 | www.Z-CERT.nl<http://www.z-cert.nl/>

Dit bericht kan informatie bevatten die niet voor u is bestemd. Indien u niet de geadresseerde bent of dit bericht abusievelijk aan u is toegezonden, wordt u verzocht dat aan de afzender te melden en het bericht te verwijderen. Z-CERT aanvaardt geen aansprakelijkheid voor schade, van welke aard ook, die verband houdt met risico's verbonden aan het elektronisch verzenden van berichten.

***@***.***

**Comment by Fxr12042** [comment]
Reproduced issue

Boefje container appears to be running:
`f24546fe8654   nl-kat-coordination_boefje                "python3 -m bin.work…"   30 minutes ago   Up 30 minutes                                                                                                                               nl-kat-coordination_boefje_1`

Error in octopoes_api log:
```[2022-09-20 12:27:41 +0000] [1] [CRITICAL] [api] 'None'
[2022-09-20 12:27:41 +0000] [1] [INFO] [h11_impl] 172.18.0.15:58370 - "GET /_dev/tree?reference=None&depth=15&valid_time=2022-09-20+12%3A27%3A41.799787%2B00%3A00 HTTP/1.1" 500
[2022-09-20 12:27:41 +0000] [1] [ERROR] [h11_impl] Exception in ASGI application
Traceback (most recent call last):
  File "/home/octopoes/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/octopoes/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/octopoes/.local/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    raise exc from None
  File "/home/octopoes/.local/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 78, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/home/octopoes/.local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/octopoes/.local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/octopoes/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/octopoes/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/octopoes/.local/lib/python3.8/site-packages/starlette/middleware/base.py", line 63, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/octopoes/.local/lib/python3.8/site-packages/fastapi_utils/timing.py", line 47, in timing_middleware
    response = await call_next(request)
  File "/home/octopoes/.local/lib/python3.8/site-packages/starlette/middleware/base.py", line 44, in call_next
    raise app_exc
  File "/home/octopoes/.local/lib/python3.8/site-packages/starlette/middleware/base.py", line 34, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/home/octopoes/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/octopoes/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/octopoes/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/octopoes/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/octopoes/.local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/octopoes/.local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/octopoes/.local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/octopoes/.local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/octopoes/.local/lib/python3.8/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/octopoes/.local/lib/python3.8/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/octopoes/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/octopoes/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/octopoes/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/octopoes_api/./octopoes/api/router.py", line 149, in get_tree
    return octopoes.get_ooi_tree(
  File "/app/octopoes_api/./octopoes/core/service.py", line 112, in get_ooi_tree
    tree = self.ooi_repository.get_tree(reference, valid_time, search_types, depth)
  File "/app/octopoes_api/./octopoes/repositories/ooi_repository.py", line 237, in get_tree
    results = self._get_tree_level({reference}, depth=depth, valid_time=valid_time)
  File "/app/octopoes_api/./octopoes/repositories/ooi_repository.py", line 283, in _get_tree_level
    reference_nodes = self._get_related_objects(references, valid_time=valid_time)
  File "/app/octopoes_api/./octopoes/repositories/ooi_repository.py", line 259, in _get_related_objects
    field_node.build_tree(1)
  File "/app/octopoes_api/./octopoes/xtdb/related_field_generator.py", line 75, in build_tree
    self.construct_outgoing_relations()
  File "/app/octopoes_api/./octopoes/xtdb/related_field_generator.py", line 36, in construct_outgoing_relations
    for foreign_key in self.data_model.entities[object_type]:
KeyError: 'None'```

**Comment by Lisser** [comment]
In the log line `[2022-09-20 12:27:41 +0000] [1] [INFO] [h11_impl] 172.18.0.15:58370 - "GET /_dev/tree?reference=None&depth=15&valid_time=2022-09-20+12%3A27%3A41.799787%2B00%3A00 HTTP/1.1" 500`

`reference=None` seems to crash Octopoes API. This None-reference probably comes from a preceding error in Rocky. Possibly Rocky was not able to save the OOI in Octopoes.

Do you have more Octopoes logs, preceding the error? We might be able to see whether the start-OOI was created at all or not.

**Comment by Fxr12042** [comment]
> In the log line `[2022-09-20 12:27:41 +0000] [1] [INFO] [h11_impl] 172.18.0.15:58370 - "GET /_dev/tree?reference=None&depth=15&valid_time=2022-09-20+12%3A27%3A41.799787%2B00%3A00 HTTP/1.1" 500`
> 
> `reference=None` seems to crash Octopoes API. This None-reference probably comes from a preceding error in Rocky. Possibly Rocky was not able to save the OOI in Octopoes.
> 
> Do you have more Octopoes logs, preceding the error? We might be able to see whether the start-OOI was created at all or not.
Sure, see attached txt file for the full log.

[log.txt](https://github.com/minvws/nl-kat-coordination/files/9645686/log.txt)

**Comment by Lisser** [comment]
Thanks. Could you send as well the results of the following `curl`?

`curl  https://<octopoes_host>/_dev/tree?reference=URL%7Cinternet%7Chttps%3A%2F%2Fwww.z-cert.nl&depth=15&valid_time=2022-09-20+12%3A27%3A41.390487%2B00%3A00`

**Comment by Fxr12042** [comment]
New install, so different timestamps:

```
curl "http://172.18.0.11/_dev/tree?reference=URL%7Cinternet%7Chttps%3A%2F%2Fwww.z-cert.nl&depth=15&valid_time=2022-09-29+09%3A21%3A55.010396%2B00%3A00"
{"root":{"reference":"URL|internet|https://www.z-cert.nl","children":{"web_url":[{"reference":"HostnameHTTPURL|https|internet|www.z-cert.nl|443|/","children":{"network":[{"reference":"Network|internet","children":{}}],"netloc":[{"reference":"Hostname|internet|www.z-cert.nl","children":{"network":[{"reference":"Network|internet","children":{}}],"fqdn":[{"reference":"Hostname|internet|www.z-cert.nl.","children":{"network":[{"reference":"Network|internet","children":{}}],"fqdn":[{"reference":"Hostname|internet|www.z-cert.nl.","children":{"network":[{"reference":"Network|internet","children":{}}],"ResolvedHostname_hostname":[{"reference":"ResolvedHostname|internet|www.z-cert.nl.|internet|104.22.0.131","children":{}},{"reference":"ResolvedHostname|internet|www.z-cert.nl.|internet|104.22.1.131","children":{}},{"reference":"ResolvedHostname|internet|www.z-cert.nl.|internet|172.67.24.222","children":{}}],"findings":[{"reference":"Finding|Hostname|internet|www.z-cert.nl.|KAT-581","children":{"finding_type":[{"reference":"KATFindingType|KAT-581","children":{}}]}}],"dns_a_records":[{"reference":"DNSARecord|internet|www.z-cert.nl.|104.22.0.131","children":{}},{"reference":"DNSARecord|internet|www.z-cert.nl.|104.22.1.131","children":{}},{"reference":"DNSARecord|internet|www.z-cert.nl.|172.67.24.222","children":{}}]}}],"ResolvedHostname_hostname":[{"reference":"ResolvedHostname|internet|www.z-cert.nl.|internet|104.22.0.131","children":{"address":[{"reference":"IPAddressV4|internet|104.22.0.131","children":{"network":[{"reference":"Network|internet","children":{}}]}}]}},{"reference":"ResolvedHostname|internet|www.z-cert.nl.|internet|104.22.1.131","children":{"address":[{"reference":"IPAddressV4|internet|104.22.1.131","children":{"network":[{"reference":"Network|internet","children":{}}]}}]}},{"reference":"ResolvedHostname|internet|www.z-cert.nl.|internet|172.67.24.222","children":{"address":[{"reference":"IPAddressV4|internet|172.67.24.222","children":{"network":[{"reference":"Network|internet","children":{}}]}}]}}],"fqdn_of":[{"reference":"Hostname|internet|www.z-cert.nl.","children":{"network":[{"reference":"Network|internet","children":{}}],"ResolvedHostname_hostname":[{"reference":"ResolvedHostname|internet|www.z-cert.nl.|internet|104.22.0.131","children":{}},{"reference":"ResolvedHostname|internet|www.z-cert.nl.|internet|104.22.1.131","children":{}},{"reference":"ResolvedHostname|internet|www.z-cert.nl.|internet|172.67.24.222","children":{}}],"findings":[{"reference":"Finding|Hostname|internet|www.z-cert.nl.|KAT-581","children":{"finding_type":[{"reference":"KATFindingType|KAT-581","children":{}}]}}],"dns_a_records":[{"reference":"DNSARecord|internet|www.z-cert.nl.|104.22.0.131","children":{}},{"reference":"DNSARecord|internet|www.z-cert.nl.|104.22.1.131","children":{}},{"reference":"DNSARecord|internet|www.z-cert.nl.|172.67.24.222","children":{}}]}}],"findings":[{"reference":"Finding|Hostname|internet|www.z-cert.nl.|KAT-581","children":{"finding_type":[{"reference":"KATFindingType|KAT-581","children":{}}]}}],"dns_a_records":[{"reference":"DNSARecord|internet|www.z-cert.nl.|104.22.0.131","children":{"address":[{"reference":"IPAddressV4|internet|104.22.0.131","children":{"network":[{"reference":"Network|internet","children":{}}]}}]}},{"reference":"DNSARecord|internet|www.z-cert.nl.|104.22.1.131","children":{"address":[{"reference":"IPAddressV4|internet|104.22.1.131","children":{"network":[{"reference":"Network|internet","children":{}}]}}]}},{"reference":"DNSARecord|internet|www.z-cert.nl.|172.67.24.222","children":{"address":[{"reference":"IPAddressV4|internet|172.67.24.222","children":{"network":[{"reference":"Network|internet","children":{}}]}}]}}]}}],"ResolvedHostname_hostname":[{"reference":"ResolvedHostname|internet|www.z-cert.nl|internet|104.22.0.131","children":{"address":[{"reference":"IPAddressV4|internet|104.22.0.131","children":{"network":[{"reference":"Network|internet","children":{}}],"ResolvedHostname_address":[{"reference":"ResolvedHostname|internet|www.z-cert.nl.|internet|104.22.0.131","children":{}}],"dns_a_records":[{"reference":"DNSARecord|internet|www.z-cert.nl.|104.22.0.131","children":{}}]}}]}},{"reference":"ResolvedHostname|internet|www.z-cert.nl|internet|104.22.1.131","children":{"address":[{"reference":"IPAddressV4|internet|104.22.1.131","children":{"network":[{"reference":"Network|internet","children":{}}],"ResolvedHostname_address":[{"reference":"ResolvedHostname|internet|www.z-cert.nl.|internet|104.22.1.131","children":{}}],"dns_a_records":[{"reference":"DNSARecord|internet|www.z-cert.nl.|104.22.1.131","children":{}}]}}]}},{"reference":"ResolvedHostname|internet|www.z-cert.nl|internet|172.67.24.222","children":{"address":[{"reference":"IPAddressV4|internet|172.67.24.222","children":{"network":[{"reference":"Network|internet","children":{}}],"ResolvedHostname_address":[{"reference":"ResolvedHostname|internet|www.z-cert.nl.|internet|172.67.24.222","children":{}}],"dns_a_records":[{"reference":"DNSARecord|internet|www.z-cert.nl.|172.67.24.222","children":{}}]}}]}}]}}]}}],"network":[{"reference":"Network|internet","children":{}}]}},"store":{"DNSARecord|internet|www.z-cert.nl.|104.22.0.131":{"object_type":"DNSARecord","scan_profile":{"reference":"DNSARecord|internet|www.z-cert.nl.|104.22.0.131","level":2,"scan_profile_type":"inherited","inheritances":[{"parent":"Hostname|internet|www.z-cert.nl.","source":"URL|internet|https://www.z-cert.nl","level":2,"depth":4}]},"primary_key":"DNSARecord|internet|www.z-cert.nl.|104.22.0.131","hostname":"Hostname|internet|www.z-cert.nl.","dns_record_type":"A","value":"104.22.0.131","ttl":5,"address":"IPAddressV4|internet|104.22.0.131"},"DNSARecord|internet|www.z-cert.nl.|104.22.1.131":{"object_type":"DNSARecord","scan_profile":{"reference":"DNSARecord|internet|www.z-cert.nl.|104.22.1.131","level":2,"scan_profile_type":"inherited","inheritances":[{"parent":"Hostname|internet|www.z-cert.nl.","source":"URL|internet|https://www.z-cert.nl","level":2,"depth":4}]},"primary_key":"DNSARecord|internet|www.z-cert.nl.|104.22.1.131","hostname":"Hostname|internet|www.z-cert.nl.","dns_record_type":"A","value":"104.22.1.131","ttl":5,"address":"IPAddressV4|internet|104.22.1.131"},"DNSARecord|internet|www.z-cert.nl.|172.67.24.222":{"object_type":"DNSARecord","scan_profile":{"reference":"DNSARecord|internet|www.z-cert.nl.|172.67.24.222","level":2,"scan_profile_type":"inherited","inheritances":[{"parent":"Hostname|internet|www.z-cert.nl.","source":"URL|internet|https://www.z-cert.nl","level":2,"depth":4}]},"primary_key":"DNSARecord|internet|www.z-cert.nl.|172.67.24.222","hostname":"Hostname|internet|www.z-cert.nl.","dns_record_type":"A","value":"172.67.24.222","ttl":5,"address":"IPAddressV4|internet|172.67.24.222"},"Finding|Hostname|internet|www.z-cert.nl.|KAT-581":{"object_type":"Finding","scan_profile":{"reference":"Finding|Hostname|internet|www.z-cert.nl.|KAT-581","level":0,"scan_profile_type":"empty"},"primary_key":"Finding|Hostname|internet|www.z-cert.nl.|KAT-581","finding_type":"KATFindingType|KAT-581","ooi":"Hostname|internet|www.z-cert.nl.","proof":null,"description":"There are no webservers with an IPv6 address.","reproduce":null},"HostnameHTTPURL|https|internet|www.z-cert.nl|443|/":{"object_type":"HostnameHTTPURL","scan_profile":{"reference":"HostnameHTTPURL|https|internet|www.z-cert.nl|443|/","level":2,"scan_profile_type":"inherited","inheritances":[{"parent":"URL|internet|https://www.z-cert.nl","source":"URL|internet|https://www.z-cert.nl","level":2,"depth":1}]},"primary_key":"HostnameHTTPURL|https|internet|www.z-cert.nl|443|/","network":"Network|internet","scheme":"https","port":443,"path":"/","netloc":"Hostname|internet|www.z-cert.nl"},"Hostname|internet|www.z-cert.nl":{"object_type":"Hostname","scan_profile":{"reference":"Hostname|internet|www.z-cert.nl","level":2,"scan_profile_type":"inherited","inheritances":[{"parent":"HostnameHTTPURL|https|internet|www.z-cert.nl|443|/","source":"URL|internet|https://www.z-cert.nl","level":2,"depth":2}]},"primary_key":"Hostname|internet|www.z-cert.nl","network":"Network|internet","name":"www.z-cert.nl","fqdn":"Hostname|internet|www.z-cert.nl.","dns_zone":null},"Hostname|internet|www.z-cert.nl.":{"object_type":"Hostname","scan_profile":{"reference":"Hostname|internet|www.z-cert.nl.","level":2,"scan_profile_type":"inherited","inheritances":[{"parent":"Hostname|internet|www.z-cert.nl","source":"URL|internet|https://www.z-cert.nl","level":2,"depth":3}]},"primary_key":"Hostname|internet|www.z-cert.nl.","network":"Network|internet","name":"www.z-cert.nl.","fqdn":"Hostname|internet|www.z-cert.nl.","dns_zone":null},"IPAddressV4|internet|104.22.0.131":{"object_type":"IPAddressV4","scan_profile":{"reference":"IPAddressV4|internet|104.22.0.131","level":2,"scan_profile_type":"inherited","inheritances":[{"parent":"ResolvedHostname|internet|www.z-cert.nl|internet|104.22.0.131","source":"URL|internet|https://www.z-cert.nl","level":2,"depth":4}]},"primary_key":"IPAddressV4|internet|104.22.0.131","address":"104.22.0.131","network":"Network|internet"},"IPAddressV4|internet|104.22.1.131":{"object_type":"IPAddressV4","scan_profile":{"reference":"IPAddressV4|internet|104.22.1.131","level":2,"scan_profile_type":"inherited","inheritances":[{"parent":"ResolvedHostname|internet|www.z-cert.nl|internet|104.22.1.131","source":"URL|internet|https://www.z-cert.nl","level":2,"depth":4}]},"primary_key":"IPAddressV4|internet|104.22.1.131","address":"104.22.1.131","network":"Network|internet"},"IPAddressV4|internet|172.67.24.222":{"object_type":"IPAddressV4","scan_profile":{"reference":"IPAddressV4|internet|172.67.24.222","level":2,"scan_profile_type":"inherited","inheritances":[{"parent":"ResolvedHostname|internet|www.z-cert.nl|internet|172.67.24.222","source":"URL|internet|https://www.z-cert.nl","level":2,"depth":4}]},"primary_key":"IPAddressV4|internet|172.67.24.222","address":"172.67.24.222","network":"Network|internet"},"KATFindingType|KAT-581":{"object_type":"KATFindingType","scan_profile":{"reference":"KATFindingType|KAT-581","level":0,"scan_profile_type":"empty"},"primary_key":"KATFindingType|KAT-581","id":"KAT-581"},"Network|internet":{"object_type":"Network","scan_profile":{"reference":"Network|internet","level":0,"scan_profile_type":"empty"},"primary_key":"Network|internet","name":"internet"},"ResolvedHostname|internet|www.z-cert.nl.|internet|104.22.0.131":{"object_type":"ResolvedHostname","scan_profile":{"reference":"ResolvedHostname|internet|www.z-cert.nl.|internet|104.22.0.131","level":2,"scan_profile_type":"inherited","inheritances":[{"parent":"Hostname|internet|www.z-cert.nl.","source":"URL|internet|https://www.z-cert.nl","level":2,"depth":4}]},"primary_key":"ResolvedHostname|internet|www.z-cert.nl.|internet|104.22.0.131","hostname":"Hostname|internet|www.z-cert.nl.","address":"IPAddressV4|internet|104.22.0.131"},"ResolvedHostname|internet|www.z-cert.nl.|internet|104.22.1.131":{"object_type":"ResolvedHostname","scan_profile":{"reference":"ResolvedHostname|internet|www.z-cert.nl.|internet|104.22.1.131","level":2,"scan_profile_type":"inherited","inheritances":[{"parent":"Hostname|internet|www.z-cert.nl.","source":"URL|internet|https://www.z-cert.nl","level":2,"depth":4}]},"primary_key":"ResolvedHostname|internet|www.z-cert.nl.|internet|104.22.1.131","hostname":"Hostname|internet|www.z-cert.nl.","address":"IPAddressV4|internet|104.22.1.131"},"ResolvedHostname|internet|www.z-cert.nl.|internet|172.67.24.222":{"object_type":"ResolvedHostname","scan_profile":{"reference":"ResolvedHostname|internet|www.z-cert.nl.|internet|172.67.24.222","level":2,"scan_profile_type":"inherited","inheritances":[{"parent":"Hostname|internet|www.z-cert.nl.","source":"URL|internet|https://www.z-cert.nl","level":2,"depth":4}]},"primary_key":"ResolvedHostname|internet|www.z-cert.nl.|internet|172.67.24.222","hostname":"Hostname|internet|www.z-cert.nl.","address":"IPAddressV4|internet|172.67.24.222"},"ResolvedHostname|internet|www.z-cert.nl|internet|104.22.0.131":{"object_type":"ResolvedHostname","scan_profile":{"reference":"ResolvedHostname|internet|www.z-cert.nl|internet|104.22.0.131","level":2,"scan_profile_type":"inherited","inheritances":[{"parent":"Hostname|internet|www.z-cert.nl","source":"URL|internet|https://www.z-cert.nl","level":2,"depth":3}]},"primary_key":"ResolvedHostname|internet|www.z-cert.nl|internet|104.22.0.131","hostname":"Hostname|internet|www.z-cert.nl","address":"IPAddressV4|internet|104.22.0.131"},"ResolvedHostname|internet|www.z-cert.nl|internet|104.22.1.131":{"object_type":"ResolvedHostname","scan_profile":{"reference":"ResolvedHostname|internet|www.z-cert.nl|internet|104.22.1.131","level":2,"scan_profile_type":"inherited","inheritances":[{"parent":"Hostname|internet|www.z-cert.nl","source":"URL|internet|https://www.z-cert.nl","level":2,"depth":3}]},"primary_key":"ResolvedHostname|internet|www.z-cert.nl|internet|104.22.1.131","hostname":"Hostname|internet|www.z-cert.nl","address":"IPAddressV4|internet|104.22.1.131"},"ResolvedHostname|internet|www.z-cert.nl|internet|172.67.24.222":{"object_type":"ResolvedHostname","scan_profile":{"reference":"ResolvedHostname|internet|www.z-cert.nl|internet|172.67.24.222","level":2,"scan_profile_type":"inherited","inheritances":[{"parent":"Hostname|internet|www.z-cert.nl","source":"URL|internet|https://www.z-cert.nl","level":2,"depth":3}]},"primary_key":"ResolvedHostname|internet|www.z-cert.nl|internet|172.67.24.222","hostname":"Hostname|internet|www.z-cert.nl","address":"IPAddressV4|internet|172.67.24.222"},"URL|internet|https://www.z-cert.nl":{"object_type":"URL","scan_profile":{"reference":"URL|internet|https://www.z-cert.nl","level":2,"scan_profile_type":"declared"},"primary_key":"URL|internet|https://www.z-cert.nl","network":"Network|internet","raw":"https://www.z-cert.nl","web_url":"HostnameHTTPURL|https|internet|www.z-cert.nl|443|/"}}}
```

**Comment by Mergpijp** [comment]
Hey, I had the same issue. I thought it was because of the third boefje I selected. But it actually was the URL starting with www. seems to generate this issue. Will be testing more with the extra boefje. Hope this helps.
