### ISSUE TITLE
Bytes exception when timestamping is enabled

### ISSUE THREAD

**Issue by dekkers** [minvws/nl-kat-coordination#3277]
**Describe the bug**
When timestamping is enabled bytes will throw an exception. The exception goes away when timestamping is disabled.

**To Reproduce**

1. Enable timestamping
2. Add a new OOI

**OpenKAT version**
1.15.1

**Additional context**
```
[2024-07-23 11:35:45 +0200] [830] [INFO] [sql_meta_repository] Added boefje meta [id=00c07768-fef1-43e4-982b-3e3ed9c6d708]
[2024-07-23 11:35:45 +0200] [830] [INFO] [h11_impl] 10.65.10.121:0 - "POST /bytes/boefje_meta HTTP/1.1" 201
[2024-07-23 11:35:46 +0200] [830] [INFO] [sql_meta_repository] Added hash sha512:92c0196d0894c63c3b463970bb6c4e83b601498247d6f48e19a6d0b88dc7c955e22f5b17537fb10568a1c6b0b757eb2d82e78b4cfd08a2e794b3509188e9a003 and link MIIFKwYJKoZIhvcNAQcCoIIFHDCCBRgCAQMxDzANBglghkgBZQMEAgMFADCCAXIGCyqGSIb3DQEJEAEEoIIBYQSCAV0wggFZAgEBBgQqAwQBMB8wBwYFKw4DAhoEFErZFEt3NbwW1OIHSvmAGaTe2FltAgQCyZVNGA8yMDI0MDcyMzA5MzU0NloBAf+gggERpIIBDTCCAQkxETAPBgNVBAoTCEZyZWUgVFNBMQwwCgYDVQQLEwNUU0ExdjB0BgNVBA0TbVRoaXMgY2VydGlmaWNhdGUgZGlnaXRhbGx5IHNpZ25zIGRvY3VtZW50cyBhbmQgdGltZSBzdGFtcCByZXF1ZXN0cyBtYWRlIHVzaW5nIHRoZSBmcmVldHNhLm9yZyBvbmxpbmUgc2VydmljZXMxGDAWBgNVBAMTD3d3dy5mcmVldHNhLm9yZzEiMCAGCSqGSIb3DQEJARYTYnVzaWxlemFzQGdtYWlsLmNvbTESMBAGA1UEBxMJV3VlcnpidXJnMQswCQYDVQQGEwJERTEPMA0GA1UECBMGQmF5ZXJuMYIDijCCA4YCAQEwgaMwgZUxETAPBgNVBAoTCEZyZWUgVFNBMRAwDgYDVQQLEwdSb290IENBMRgwFgYDVQQDEw93d3cuZnJlZXRzYS5vcmcxIjAgBgkqhkiG9w0BCQEWE2J1c2lsZXphc0BnbWFpbC5jb20xEjAQBgNVBAcTCVd1ZXJ6YnVyZzEPMA0GA1UECBMGQmF5ZXJuMQswCQYDVQQGEwJERQIJAMHphhYNqOmCMA0GCWCGSAFlAwQCAwUAoIG4MBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAcBgkqhkiG9w0BCQUxDxcNMjQwNzIzMDkzNTQ2WjArBgsqhkiG9w0BCRACDDEcMBowGDAWBBSRbaPYYOzKguNLxZ0Xk+fpaIdfFDBPBgkqhkiG9w0BCQQxQgRALElW4zJEvekhEuYAD+oJkAfHWZM+u7EeDqeCFzrwp6kaFd/yRlslBEu4bIhjg2HjpVi42Ouw3iS8SqrLmpsEQzANBgkqhkiG9w0BAQEFAASCAgBpvlXh3ZQgHQG4xY9ljhixHENcCtk38GgQVGm10OFKpdDHf6mdlOyt1X+Tx1gDOsI3dMeMZD5+Van0zBHw/zTU3eBZLszKfcEyQ18/I9l+Zm0vyniR0iafD3IbvCDq4C6wDTYpZE2BcOE0yBi/FENzSSqnCb7l0mK5K/k+PiW0hNCBNXKSm54X1qAx5bZjxsV+AqzmuQIAYnQPssqoCt63xxPaK0Oidyzj4qJLfkz2SnR1ayakHC84LP6WAUM4gt5DEKCefPfwx2a5pCx+wjQcveH+4k1J7CUXRjwZi7p/6NbTkDwnpq6jVqxuO7sCQybiE/71v/xV/KO3CngYc/3DQ2wGfftZUnP2glVfbQNEgDz4s5cgWtRrUyZVvGnZFcfyG1c1rEpz+Ls805K6ZmFthpEcLovg5cxvXHtOERx5ilW29qJuDwVwGm3DnPN7CmdtY28tQF63jgmtxoPfu+bK4hftn8Vhkk4RzYQ8JihQKz+LV9OpVbbgsgqOXve7RLsGgCaP/xzhSTMO4R2ohoplix7+D5Ds8CBL/sNzHuZB3tvuuVRAnKbCjLPtAxWU0FsLzjUB5V0/t1P1oy8yQcNp+XPRKMRFwINCAaorkcPeeO7ilpJ4iyLKeAta+RIb1U71wAh5dw5Si83jesYy/0Sj1n/4OGOQf1jGGjkr7bMlDw== to data
[2024-07-23 11:35:46 +0200] [830] [ERROR] [router] Error saving raw data
Traceback (most recent call last):
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: can't adapt type 'pydantic_core._pydantic_core.Url'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/var/www/bytes_v1.15.1/bytes/api/router.py", line 166, in create_raw
    raw_id = meta_repository.save_raw(raw_data)
  File "/var/www/bytes_v1.15.1/bytes/database/sql_meta_repository.py", line 127, in save_raw
    signing_provider = self._get_or_create_signing_provider(raw.signing_provider_url)
  File "/var/www/bytes_v1.15.1/bytes/database/sql_meta_repository.py", line 199, in _get_or_create_signing_provider
    signing_provider = query.first()
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2824, in first
    return self.limit(1)._iter().first()
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'pydantic_core._pydantic_core.Url'
[SQL: SELECT signing_provider.id AS signing_provider_id, signing_provider.url AS signing_provider_url
FROM signing_provider
WHERE signing_provider.url = %(url_1)s
 LIMIT %(param_1)s]
[parameters: {'url_1': Url('https://freetsa.org/tsr'), 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-07-23 11:35:46 +0200] [830] [ERROR] [sql_meta_repository] An error occurred during the session.
Traceback (most recent call last):
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: can't adapt type 'pydantic_core._pydantic_core.Url'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/var/www/bytes_v1.15.1/bytes/api/router.py", line 166, in create_raw
    raw_id = meta_repository.save_raw(raw_data)
  File "/var/www/bytes_v1.15.1/bytes/database/sql_meta_repository.py", line 127, in save_raw
    signing_provider = self._get_or_create_signing_provider(raw.signing_provider_url)
  File "/var/www/bytes_v1.15.1/bytes/database/sql_meta_repository.py", line 199, in _get_or_create_signing_provider
    signing_provider = query.first()
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2824, in first
    return self.limit(1)._iter().first()
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/var/www/html/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'pydantic_core._pydantic_core.Url'
[SQL: SELECT signing_provider.id AS signing_provider_id, signing_provider.url AS signing_provider_url
FROM signing_provider
WHERE signing_provider.url = %(url_1)s
 LIMIT %(param_1)s]
[parameters: {'url_1': Url('https://freetsa.org/tsr'), 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/14/f405)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/var/www/bytes_v1.15.1/bytes/database/sql_meta_repository.py", line 219, in create_meta_data_repository
    yield repository
fastapi.exceptions.HTTPException: 500: Could not save raw data
[2024-07-23 11:35:46 +0200] [830] [WARNING] [sql_meta_repository] Rolled back session.
[2024-07-23 11:35:46 +0200] [830] [INFO] [h11_impl] 10.65.10.121:0 - "POST /bytes/raw?mime_types=boefje%2Fmanual&mime_types=manual%2Fooi&boefje_meta_id=00c07768-fef1-43e4-982b-3e3ed9c6d708 HTTP/1.1" 500

```

**Comment by underdarknl** [comment]
https://docs.pydantic.dev/latest/migration/#url-and-dsn-types-in-pydanticnetworks-no-longer-inherit-from-str
I think we missed this migration.

**Comment by sigio** [comment]
Fix applied, seems to work
