### ISSUE TITLE
Burp normalizer json error 

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3537]
**Describe the bug**
Uploading a burpsuite file now works. The normalizer throws an error as shown below. 

**To Reproduce**

1. Upload a burpsuite xml file

**Expected behavior**
The burpsuite xml file is parsed by the normalizer and creates findings. 

**OpenKAT version**
commit 461519a3807cbe69f604c0a732bd4a34c7f2aa6b (HEAD -> fix/burpsuite-import, origin/fix/burpsuite-import)

```
normalizer-1  | [2024-09-16 11:16:24 +0000] [15] [ERROR] [app] {"exc_info": true, "event": "An error occurred handling scheduler item[id=b30e005c-cb22-4462-aeb4-d690f6f5779d]", "level": "error", "timestamp": "2
024-09-16T11:16:24.517017"}
normalizer-1  | Traceback (most recent call last):
normalizer-1  |   File "/app/boefjes/boefjes/app.py", line 248, in _start_working
normalizer-1  |     handler.handle(p_item.data)
normalizer-1  |   File "/app/boefjes/boefjes/job_handler.py", line 184, in handle
normalizer-1  |     results = self.job_runner.run(normalizer_meta, raw)
normalizer-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
normalizer-1  |   File "/app/boefjes/boefjes/local.py", line 86, in run
normalizer-1  |     return self._parse_results(normalizer_meta, results)
normalizer-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
normalizer-1  |   File "/app/boefjes/boefjes/local.py", line 94, in _parse_results
normalizer-1  |     for result in results:
normalizer-1  |   File "/app/boefjes/boefjes/plugins/kat_dns/normalize.py", line 42, in run
normalizer-1  |     results = json.loads(raw)
normalizer-1  |               ^^^^^^^^^^^^^^^
normalizer-1  |   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
normalizer-1  |     return _default_decoder.decode(s)
normalizer-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
normalizer-1  |   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
normalizer-1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
normalizer-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
normalizer-1  |   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
normalizer-1  |     raise JSONDecodeError("Expecting value", s, err.value) from None
normalizer-1  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by noamblitz** [comment]
This looks like the dns normalizer. Are you sure you put the correct mime type?

**Comment by stephanie0x00** [comment]
Derp my bad. I blame the broken coffee machine. It totally works now :see_no_evil:
