### ISSUE TITLE
RecursionError at /en/dev/reports/multi-report/select/oois/

### ISSUE THREAD

**Issue by jpbruinsslot** [minvws/nl-kat-coordination#3623]
**Describe the bug**

RecursionError at /en/dev/reports/multi-report/select/oois/ when accessing the "Multi report page"

**To Reproduce**

1. Go to "Reports" tab
2. Click on "Generate report"
3. Click on "Multi report" tab

**Expected behavior**

Load multi report form

**Screenshots**

![Screenshot from 2024-10-07 09-42-01](https://github.com/user-attachments/assets/27a4a69c-cf52-40e7-9020-975e7a929583)

**Traceback**

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/en/dev/reports/multi-report/select/oois/?clearance_level=2&clearance_level=3&clearance_level=4&clearance_type=declared

Django Version: 5.0.8
Python Version: 3.11.10
Installed Applications:
['whitenoise.runserver_nostatic',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.humanize',
 'django.forms',
 'django_components',
 'django_components.safer_staticfiles',
 'django_otp',
 'django_otp.plugins.otp_static',
 'django_otp.plugins.otp_totp',
 'two_factor',
 'account',
 'tools',
 'fmea',
 'rocky',
 'crisis_room',
 'onboarding',
 'katalogus',
 'django_password_validators',
 'django_password_validators.password_history',
 'rest_framework',
 'tagulous',
 'compressor',
 'reports',
 'knox',
 'csp']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'rocky.middleware.auth_token.AuthTokenMiddleware',
 'django_structlog.middlewares.RequestMiddleware',
 'django_otp.middleware.OTPMiddleware',
 'rocky.middleware.auth_required.AuthRequiredMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'rocky.middleware.onboarding.OnboardingMiddleware',
 'rocky.middleware.otel.OTELInstrumentTemplateMiddleware',
 'csp.middleware.CSPMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/rocky/reports/views/multi_report.py", line 84, in get
    return self.get(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/rocky/reports/views/multi_report.py", line 84, in get
    return self.get(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/rocky/reports/views/multi_report.py", line 83, in get
    messages.error(request, self.NONE_OOI_SELECTION_MESSAGE)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/messages/api.py", line 121, in error
    add_message(
    ^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/messages/api.py", line 40, in add_message
    return messages.add(level, message, extra_tags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/messages/storage/base.py", line 149, in add
    if not message:
    ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/translation/__init__.py", line 96, in gettext
    return _trans.gettext(message)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/translation/trans_real.py", line 382, in gettext
    translation_object = getattr(_active, "value", _default)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/local.py", line 101, in __getattr__
    storage = self._get_storage()
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/local.py", line 81, in _get_storage
    context_obj = self._get_context_id()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/local.py", line 49, in _get_context_id
    from .sync import AsyncToSync, SyncToAsync
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 409, in parent
    <source code not available>
                       ^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: RecursionError at /en/dev/reports/multi-report/select/oois/
Exception Value: maximum recursion depth exceeded while calling a Python object

```

**OpenKAT version**

main 8d40832031d24d7b839b17386155e12c3f0a64d1

**Desktop (please complete the following information if relevant):**

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Additional context**

**Comment by dekkers** [comment]
https://sonarcloud.io/project/issues?fileUuids=AY_dVgiJGgO8mB8X8A1A&issueStatuses=OPEN%2CCONFIRMED&id=minvws_nl-kat-coordination&open=AZJXrRL4dScQYYDmeUzN
