### ISSUE TITLE
Error when scheduled report is created in the worker

### ISSUE THREAD

**Issue by dekkers** [minvws/nl-kat-coordination#3675]
A scheduled report results in the following error:

```
2024-10-11T12:34:27.492427 [error] An error occurred handling scheduler item[id=1dbbeb4a-f003-47b2-b538-9b71ee0f335b]
Traceback (most recent call last):
  File "/opt/venvs/kat-rocky/lib/python3.11/site-packages/reports/runner/worker.py", line 235, in _start_working
    runner.run(p_item.data)
  File "/opt/venvs/kat-rocky/lib/python3.11/site-packages/reports/runner/local.py", line 37, in run
    save_report_data(
  File "/opt/venvs/kat-rocky/lib/python3.11/site-packages/reports/views/mixins.py", line 90, in save_report_data
    input_oois=input_data["input_data"]["input_oois"],
               ~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

**Comment by dekkers** [comment]
This seems to have been fixed, because I don't see the exception anymore.
