### ISSUE TITLE
Report recipe editing page misses front end check on cron

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3741]
**Describe the bug**
The editing page for the report recipes misses a front-end check to verify if the input is expected and allowed. By providing an unexpected value (e.g. the letter A) a Schedule error is thrown. 

**To Reproduce**

1. Edit a report recipe.
2. Enter the value 'a' in the cron field.
3. Save

**Expected behavior**
Unexpected values should be caught by the front- and back-end, to make malicious attacks more difficult and also offering a better user experience. 

**Screenshots**
![image](https://github.com/user-attachments/assets/2201d158-1e2e-4c9f-bbfc-f804734e1ba6)

**OpenKAT version**
main

```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/en/aa/objects/edit/?ooi_id=ReportRecipe%7C1417a276-d55f-4964-9c53-1f38bdfcfc05

Django Version: 5.0.9
Python Version: 3.11.10
Installed Applications:
['whitenoise.runserver_nostatic',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.humanize',
 'django.forms',
 'django_components',
 'django_components.safer_staticfiles',
 'django_otp',
 'django_otp.plugins.otp_static',
 'django_otp.plugins.otp_totp',
 'two_factor',
 'account',
 'tools',
 'fmea',
 'rocky',
 'crisis_room',
 'onboarding',
 'katalogus',
 'django_password_validators',
 'django_password_validators.password_history',
 'rest_framework',
 'tagulous',
 'compressor',
 'reports',
 'knox',
 'csp']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'rocky.middleware.auth_token.AuthTokenMiddleware',
 'django_structlog.middlewares.RequestMiddleware',
 'django_otp.middleware.OTPMiddleware',
 'rocky.middleware.auth_required.AuthRequiredMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'rocky.middleware.onboarding.OnboardingMiddleware',
 'csp.middleware.CSPMiddleware']



Traceback (most recent call last):
  File "/app/rocky/rocky/scheduler.py", line 300, in patch_schedule
    response.raise_for_status()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

During handling of the above exception (Client error '400 Bad Request' for url 'http://scheduler:8000/schedules/519a331d-d0a3-4014-a9f1-3da5c2bd1ea1'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400), another exception occurred:
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/rocky/rocky/views/ooi_edit.py", line 57, in form_valid
    self.edit_report_schedule(schedule_id, {"schedule": cron_expression, "deadline_at": deadline_at})
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/rocky/rocky/views/scheduler.py", line 140, in edit_report_schedule
    self.scheduler_client.patch_schedule(schedule_id=schedule_id, params=params)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/rocky/rocky/scheduler.py", line 302, in patch_schedule
    raise SchedulerHTTPError()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: SchedulerHTTPError at /en/aa/objects/edit/
Exception Value: A HTTPError occurred. See Scheduler logs for more info.
```

**Comment by underdarknl** [comment]
The scheduler should indicate the type of issue it saw by specifying this as such:
invalid schedule [exception: {exc}]

We should be able to catch this in the schedulerClient and raise an appropriate error to the frontend/user based on this backend error.
