### ISSUE TITLE
rocky's healt page seems to crash when the underlying octopoes files to reach the xtdb instance.

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#393]
The rocky health page seems to crash instead of return a nicely formatted error page
Looks like it (or octopoes) cannot reach XTDB.

```
Nov  7 10:42:53 he91 python[642769]: [2022-11-07 11:42:53 +0100] [642769] [ERROR] [router] HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /_xtdb/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f6c6e46d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Nov  7 10:42:53 he91 [2022-11-07 11:42:53 +0100] [642769] [ERROR] [router] HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /_xtdb/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f6c6e46d0>: Failed to establish a new connection: [Errno 111] Connection refused'))#012Traceback (most recent call last):#012  File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn#012    conn = connection.create_connection(#012  File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection#012    raise err#012  File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection#012 sock.connect(sa)#012ConnectionRefusedError: [Errno 111] Connection refused#012#012During handling of the above exception, another exception occurred:#012#012Traceback (most recent call last):#012 File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen#012    httplib_response = self._make_request(#012  File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request#012    conn.request(method, url, **httplib_request_kw)#012  File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request#012    super(HTTPConnection, self).request(method, url, body=body, headers=headers)#012  File "/usr/lib/python3.9/http/client.py", line 1255, in request#012 self._send_request(method, url, body, headers, encode_chunked)#012 File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request#012    self.endheaders(body, encode_chunked=encode_chunked)#012  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders#012 self._send_output(message_body, encode_chunked=encode_chunked)#012 File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output#012    self.send(msg)#012  File "/usr/lib/python3.9/http/client.py", line 950, in send#012 self.connect()#012  File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect#012    conn = self._new_conn()#012  File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn#012    raise NewConnectionError(#012urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5f6c6e46d0>: Failed to establish a new connection: [Errno 111] Connection refused#012#012During handling of the above exception, another exception occurred:#012#012Traceback (most recent call last):#012 File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/requests/adapters.py", line 440, in send#012    resp = conn.urlopen(#012  File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen#012    retries = retries.increment(#012  File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment#012    raise MaxRetryError(_pool, url, error or ResponseError(cause))#012urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /_xtdb/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f6c6e46d0>: Failed to establish a new connection: [Errno 111] Connection refused'))#012#012During handling of the above exception, another exception occurred:#012#012Traceback (most recent call last):#012  File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/octopoes/api/router.py", line 79, in health#012    xtdb_status = xtdb.status()#012  File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/octopoes/xtdb/client.py", line 69, in status#012    res = self._session.get("/status")#012 File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/requests/sessions.py", line 542, in get#012    return self.request('GET', url, **kwargs)#012  File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/octopoes/xtdb/client.py", line 40, in request#012    return super().request(method, self._base_url + str(url), **kwargs)#012  File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/requests/sessions.py", line 529, in request#012    resp = self.send(prep, **send_kwargs)#012  File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/requests/sessions.py", line 645, in send#012    r = adapter.send(request, **kwargs)#012 File "/opt/venvs/kat-octopoes/lib/python3.9/site-packages/requests/adapters.py", line 519, in send#012    raise ConnectionError(e, request=request)#012requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /_xtdb/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f6c6e46d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Nov  7 10:42:53 he91 python[729646]: [2022-11-07 11:42:53 +0100] [729646] [ERROR] [h11_impl] [uvicorn.error] Exception in ASGI application
Nov  7 10:42:53 he91 uwsgi[713253]: ERROR:django.request:Internal Server Error: /health/
```

**Comment by underdarknl** [comment]
Seems to work
