### ISSUE TITLE
KeyError in Question object answer parser normalizer

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3958]
**Describe the bug**
When applying the config from a Question object, the Answer parser fails and throws an error in the logs. 

**To Reproduce**

1. Save the answer to a question object.
2. Check the Normalizer tasks
3. Check normalizer logs for the error. 

**Expected behavior**
The anwser parser completes when a question is submitted.

**Screenshots**
![Image](https://github.com/user-attachments/assets/d7570525-f545-406d-b079-c1baa78c88cd)

**OpenKAT version**
Note the release tag (and if possible: the installation method) here.
If it concerns an in-development version, note the branch(es) and commit hash(es) here as well.

```
normalizer-1  | 2024-12-12T08:34:01.699797 [info] Handling normalizer kat_answer_parser[078ec3b5-bce6-4c09-b5b0-f9a7a9c5e869]
normalizer-1  | HTTP Request: GET http://bytes:8000/bytes/raw/ae276311-0089-426d-9e99-43f0fae2c003 "HTTP/1.1 401 Unauthorized"
normalizer-1  | HTTP Request: POST http://bytes:8000/token "HTTP/1.1 200 OK"
normalizer-1  | HTTP Request: GET http://bytes:8000/bytes/raw/ae276311-0089-426d-9e99-43f0fae2c003 "HTTP/1.1 200 OK"
normalizer-1  | HTTP Request: POST http://bytes:8000/bytes/normalizer_meta "HTTP/1.1 201 Created"
normalizer-1  | 2024-12-12T08:34:02.204210 [error] An error occurred handling scheduler item[id=078ec3b5-bce6-4c09-b5b0-f9a7a9c5e869]
normalizer-1  | ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
normalizer-1  | │ /app/boefjes/boefjes/app.py:251 in _start_working                                                │
normalizer-1  | │                                                                                                  │
normalizer-1  | │   248 │   │                                                                                      │
normalizer-1  | │   249 │   │   try:                                                                               │
normalizer-1  | │   250 │   │   │   scheduler_client.patch_task(p_item.id, TaskStatus.RUNNING)                     │
normalizer-1  | │ ❱ 251 │   │   │   handler.handle(p_item.data)                                                    │
normalizer-1  | │   252 │   │   │   status = TaskStatus.COMPLETED                                                  │
normalizer-1  | │   253 │   │   except Exception:  # noqa                                                          │
normalizer-1  | │   254 │   │   │   logger.exception("An error occurred handling scheduler item[id=%s]", p_item.   │
normalizer-1  | │                                                                                                  │
normalizer-1  | │ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
normalizer-1  | │ │          handler = <boefjes.job_handler.NormalizerHandler object at 0x787b4b324b50>          │ │
normalizer-1  | │ │   handling_tasks = <DictProxy object, typeid 'dict' at 0x787b4b4a8090>                       │ │
normalizer-1  | │ │           p_item = Task(                                                                     │ │
normalizer-1  | │ │                    │   id=UUID('078ec3b5-bce6-4c09-b5b0-f9a7a9c5e869'),                      │ │
normalizer-1  | │ │                    │   scheduler_id='normalizer-aa',                                         │ │
normalizer-1  | │ │                    │   schedule_id=None,                                                     │ │
normalizer-1  | │ │                    │   priority=1,                                                           │ │
normalizer-1  | │ │                    │   status=<TaskStatus.DISPATCHED: 'dispatched'>,                         │ │
normalizer-1  | │ │                    │   type='normalizer',                                                    │ │
normalizer-1  | │ │                    │   hash='2b0b0b85453a81f99d802b5c3eb952ba',                              │ │
normalizer-1  | │ │                    │   data=NormalizerMeta(                                                  │ │
normalizer-1  | │ │                    │   │   id=UUID('078ec3b5-bce6-4c09-b5b0-f9a7a9c5e869'),                  │ │
normalizer-1  | │ │                    │   │   started_at=datetime.datetime(2024, 12, 12, 8, 34, 2, 148181,      │ │
normalizer-1  | │ │                    tzinfo=datetime.timezone.utc),                                            │ │
normalizer-1  | │ │                    │   │   ended_at=datetime.datetime(2024, 12, 12, 8, 34, 2, 148407,        │ │
normalizer-1  | │ │                    tzinfo=datetime.timezone.utc),                                            │ │
normalizer-1  | │ │                    │   │   raw_data=RawDataMeta(                                             │ │
normalizer-1  | │ │                    │   │   │   id=UUID('ae276311-0089-426d-9e99-43f0fae2c003'),              │ │
normalizer-1  | │ │                    │   │   │   boefje_meta=BoefjeMeta(                                       │ │
normalizer-1  | │ │                    │   │   │   │   id=UUID('d08291d7-fd9b-4835-9dfc-2dde76201fcf'),          │ │
normalizer-1  | │ │                    │   │   │   │   started_at=datetime.datetime(2024, 12, 12, 7, 19, 11,     │ │
normalizer-1  | │ │                    691374, tzinfo=TzInfo(UTC)),                                              │ │
normalizer-1  | │ │                    │   │   │   │   ended_at=datetime.datetime(2024, 12, 12, 7, 19, 11,       │ │
normalizer-1  | │ │                    691376, tzinfo=TzInfo(UTC)),                                              │ │
normalizer-1  | │ │                    │   │   │   │   boefje=Boefje(id='manual', version=None),                 │ │
normalizer-1  | │ │                    │   │   │   │   input_ooi='Network|internet',                             │ │
normalizer-1  | │ │                    │   │   │   │   arguments={},                                             │ │
normalizer-1  | │ │                    │   │   │   │   organization='aa',                                        │ │
normalizer-1  | │ │                    │   │   │   │   runnable_hash=None,                                       │ │
normalizer-1  | │ │                    │   │   │   │   environment=None                                          │ │
normalizer-1  | │ │                    │   │   │   ),                                                            │ │
normalizer-1  | │ │                    │   │   │   mime_types=[                                                  │ │
normalizer-1  | │ │                    │   │   │   │   {'value': '/bit/disallowed-csp-hostnames'},               │ │
normalizer-1  | │ │                    │   │   │   │   {'value': 'boefje/manual'},                               │ │
normalizer-1  | │ │                    │   │   │   │   {'value': 'answer'}                                       │ │
normalizer-1  | │ │                    │   │   │   ]                                                             │ │
normalizer-1  | │ │                    │   │   ),                                                                │ │
normalizer-1  | │ │                    │   │   normalizer=Normalizer(id='kat_answer_parser', version=None)       │ │
normalizer-1  | │ │                    │   ),                                                                    │ │
normalizer-1  | │ │                    │   created_at=datetime.datetime(2024, 12, 12, 8, 33, 58, 708509,         │ │
normalizer-1  | │ │                    tzinfo=TzInfo(UTC)),                                                      │ │
normalizer-1  | │ │                    │   modified_at=datetime.datetime(2024, 12, 12, 8, 33, 58, 708516,        │ │
normalizer-1  | │ │                    tzinfo=TzInfo(UTC))                                                       │ │
normalizer-1  | │ │                    )                                                                         │ │
normalizer-1  | │ │ scheduler_client = <boefjes.clients.scheduler_client.SchedulerAPIClient object at            │ │
normalizer-1  | │ │                    0x787b49709910>                                                           │ │
normalizer-1  | │ │           status = <TaskStatus.FAILED: 'failed'>                                             │ │
normalizer-1  | │ │       task_queue = <AutoProxy[Queue] object, typeid 'Queue' at 0x787b49caa090>               │ │
normalizer-1  | │ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
normalizer-1  | │                                                                                                  │
normalizer-1  | │ /app/boefjes/boefjes/job_handler.py:199 in handle                                                │
normalizer-1  | │                                                                                                  │
normalizer-1  | │   196 │   │   normalizer_meta.started_at = datetime.now(timezone.utc)                            │
normalizer-1  | │   197 │   │                                                                                      │
normalizer-1  | │   198 │   │   try:                                                                               │
normalizer-1  | │ ❱ 199 │   │   │   results = self.job_runner.run(normalizer_meta, raw)                            │
normalizer-1  | │   200 │   │   │   connector = self.octopoes_factory(normalizer_meta.raw_data.boefje_meta.organ   │
normalizer-1  | │   201 │   │   │                                                                                  │
normalizer-1  | │   202 │   │   │   logger.info("Obtained results %s", str(results))                               │
normalizer-1  | │                                                                                                  │
normalizer-1  | │ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
normalizer-1  | │ │ normalizer_meta = NormalizerMeta(                                                            │ │
normalizer-1  | │ │                   │   id=UUID('078ec3b5-bce6-4c09-b5b0-f9a7a9c5e869'),                       │ │
normalizer-1  | │ │                   │   started_at=datetime.datetime(2024, 12, 12, 8, 34, 2, 148181,           │ │
normalizer-1  | │ │                   tzinfo=datetime.timezone.utc),                                             │ │
normalizer-1  | │ │                   │   ended_at=datetime.datetime(2024, 12, 12, 8, 34, 2, 148407,             │ │
normalizer-1  | │ │                   tzinfo=datetime.timezone.utc),                                             │ │
normalizer-1  | │ │                   │   raw_data=RawDataMeta(                                                  │ │
normalizer-1  | │ │                   │   │   id=UUID('ae276311-0089-426d-9e99-43f0fae2c003'),                   │ │
normalizer-1  | │ │                   │   │   boefje_meta=BoefjeMeta(                                            │ │
normalizer-1  | │ │                   │   │   │   id=UUID('d08291d7-fd9b-4835-9dfc-2dde76201fcf'),               │ │
normalizer-1  | │ │                   │   │   │   started_at=datetime.datetime(2024, 12, 12, 7, 19, 11, 691374,  │ │
normalizer-1  | │ │                   tzinfo=TzInfo(UTC)),                                                       │ │
normalizer-1  | │ │                   │   │   │   ended_at=datetime.datetime(2024, 12, 12, 7, 19, 11, 691376,    │ │
normalizer-1  | │ │                   tzinfo=TzInfo(UTC)),                                                       │ │
normalizer-1  | │ │                   │   │   │   boefje=Boefje(id='manual', version=None),                      │ │
normalizer-1  | │ │                   │   │   │   input_ooi='Network|internet',                                  │ │
normalizer-1  | │ │                   │   │   │   arguments={},                                                  │ │
normalizer-1  | │ │                   │   │   │   organization='aa',                                             │ │
normalizer-1  | │ │                   │   │   │   runnable_hash=None,                                            │ │
normalizer-1  | │ │                   │   │   │   environment=None                                               │ │
normalizer-1  | │ │                   │   │   ),                                                                 │ │
normalizer-1  | │ │                   │   │   mime_types=[                                                       │ │
normalizer-1  | │ │                   │   │   │   {'value': '/bit/disallowed-csp-hostnames'},                    │ │
normalizer-1  | │ │                   │   │   │   {'value': 'boefje/manual'},                                    │ │
normalizer-1  | │ │                   │   │   │   {'value': 'answer'}                                            │ │
normalizer-1  | │ │                   │   │   ]                                                                  │ │
normalizer-1  | │ │                   │   ),                                                                     │ │
normalizer-1  | │ │                   │   normalizer=Normalizer(id='kat_answer_parser', version=None)            │ │
normalizer-1  | │ │                   )                                                                          │ │
normalizer-1  | │ │             raw = b'{"disallowed_hostnames":"githubpages.com,github.io,jsdelivr.com,cdn.sky… │ │
normalizer-1  | │ │            self = <boefjes.job_handler.NormalizerHandler object at 0x787b4b324b50>           │ │
normalizer-1  | │ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
normalizer-1  | │                                                                                                  │
normalizer-1  | │ /app/boefjes/boefjes/local.py:86 in run                                                          │
normalizer-1  | │                                                                                                  │
normalizer-1  | │    83 │   │   except BaseException as e:                                                         │
normalizer-1  | │    84 │   │   │   raise JobRuntimeError("Normalizer failed") from e                              │
normalizer-1  | │    85 │   │                                                                                      │
normalizer-1  | │ ❱  86 │   │   return self._parse_results(normalizer_meta, results)                               │
normalizer-1  | │    87 │                                                                                          │
normalizer-1  | │    88 │   def _parse_results(self, normalizer_meta: NormalizerMeta, results: Iterable[Normaliz   │
normalizer-1  | │    89 │   │   oois = []                                                                          │
normalizer-1  | │                                                                                                  │
normalizer-1  | │ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
normalizer-1  | │ │       input_ooi = {'primary_key': 'Network|internet'}                                        │ │
normalizer-1  | │ │      normalizer = <boefjes.plugins.models.NormalizerResource object at 0x787b4979da90>       │ │
normalizer-1  | │ │ normalizer_meta = NormalizerMeta(                                                            │ │
normalizer-1  | │ │                   │   id=UUID('078ec3b5-bce6-4c09-b5b0-f9a7a9c5e869'),                       │ │
normalizer-1  | │ │                   │   started_at=datetime.datetime(2024, 12, 12, 8, 34, 2, 148181,           │ │
normalizer-1  | │ │                   tzinfo=datetime.timezone.utc),                                             │ │
normalizer-1  | │ │                   │   ended_at=datetime.datetime(2024, 12, 12, 8, 34, 2, 148407,             │ │
normalizer-1  | │ │                   tzinfo=datetime.timezone.utc),                                             │ │
normalizer-1  | │ │                   │   raw_data=RawDataMeta(                                                  │ │
normalizer-1  | │ │                   │   │   id=UUID('ae276311-0089-426d-9e99-43f0fae2c003'),                   │ │
normalizer-1  | │ │                   │   │   boefje_meta=BoefjeMeta(                                            │ │
normalizer-1  | │ │                   │   │   │   id=UUID('d08291d7-fd9b-4835-9dfc-2dde76201fcf'),               │ │
normalizer-1  | │ │                   │   │   │   started_at=datetime.datetime(2024, 12, 12, 7, 19, 11, 691374,  │ │
normalizer-1  | │ │                   tzinfo=TzInfo(UTC)),                                                       │ │
normalizer-1  | │ │                   │   │   │   ended_at=datetime.datetime(2024, 12, 12, 7, 19, 11, 691376,    │ │
normalizer-1  | │ │                   tzinfo=TzInfo(UTC)),                                                       │ │
normalizer-1  | │ │                   │   │   │   boefje=Boefje(id='manual', version=None),                      │ │
normalizer-1  | │ │                   │   │   │   input_ooi='Network|internet',                                  │ │
normalizer-1  | │ │                   │   │   │   arguments={},                                                  │ │
normalizer-1  | │ │                   │   │   │   organization='aa',                                             │ │
normalizer-1  | │ │                   │   │   │   runnable_hash=None,                                            │ │
normalizer-1  | │ │                   │   │   │   environment=None                                               │ │
normalizer-1  | │ │                   │   │   ),                                                                 │ │
normalizer-1  | │ │                   │   │   mime_types=[                                                       │ │
normalizer-1  | │ │                   │   │   │   {'value': '/bit/disallowed-csp-hostnames'},                    │ │
normalizer-1  | │ │                   │   │   │   {'value': 'boefje/manual'},                                    │ │
normalizer-1  | │ │                   │   │   │   {'value': 'answer'}                                            │ │
normalizer-1  | │ │                   │   │   ]                                                                  │ │
normalizer-1  | │ │                   │   ),                                                                     │ │
normalizer-1  | │ │                   │   normalizer=Normalizer(id='kat_answer_parser', version=None)            │ │
normalizer-1  | │ │                   )                                                                          │ │
normalizer-1  | │ │     normalizers = {                                                                          │ │
normalizer-1  | │ │                   │   'kat_adr_finding_types_normalize':                                     │ │
normalizer-1  | │ │                   <boefjes.plugins.models.NormalizerResource object at 0x787b49a710d0>,      │ │
normalizer-1  | │ │                   │   'adr-validator-normalize': <boefjes.plugins.models.NormalizerResource  │ │
normalizer-1  | │ │                   object at 0x787b49a5c810>,                                                 │ │
normalizer-1  | │ │                   │   'kat_answer_parser': <boefjes.plugins.models.NormalizerResource object │ │
normalizer-1  | │ │                   at 0x787b4979da90>,                                                        │ │
normalizer-1  | │ │                   │   'kat_binaryedge_containers':                                           │ │
normalizer-1  | │ │                   <boefjes.plugins.models.NormalizerResource object at 0x787b49759750>,      │ │
normalizer-1  | │ │                   │   'kat_binaryedge_databases': <boefjes.plugins.models.NormalizerResource │ │
normalizer-1  | │ │                   object at 0x787b4975ac90>,                                                 │ │
normalizer-1  | │ │                   │   'kat_binaryedge_http_web': <boefjes.plugins.models.NormalizerResource  │ │
normalizer-1  | │ │                   object at 0x787b4975b2d0>,                                                 │ │
normalizer-1  | │ │                   │   'kat_binaryedge_message_queues':                                       │ │
normalizer-1  | │ │                   <boefjes.plugins.models.NormalizerResource object at 0x787b4975ba10>,      │ │
normalizer-1  | │ │                   │   'kat_binaryedge_protocols': <boefjes.plugins.models.NormalizerResource │ │
normalizer-1  | │ │                   object at 0x787b49610090>,                                                 │ │
normalizer-1  | │ │                   │   'kat_binaryedge_remote_desktop':                                       │ │
normalizer-1  | │ │                   <boefjes.plugins.models.NormalizerResource object at 0x787b49610b50>,      │ │
normalizer-1  | │ │                   │   'kat_binaryedge_service_identification':                               │ │
normalizer-1  | │ │                   <boefjes.plugins.models.NormalizerResource object at 0x787b4975ac10>,      │ │
normalizer-1  | │ │                   │   ... +46                                                                │ │
normalizer-1  | │ │                   }                                                                          │ │
normalizer-1  | │ │             raw = b'{"disallowed_hostnames":"githubpages.com,github.io,jsdelivr.com,cdn.sky… │ │
normalizer-1  | │ │         results = <generator object run at 0x787b49770240>                                   │ │
normalizer-1  | │ │            self = <boefjes.local.LocalNormalizerJobRunner object at 0x787b49a717d0>          │ │
normalizer-1  | │ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
normalizer-1  | │                                                                                                  │
normalizer-1  | │ /app/boefjes/boefjes/local.py:94 in _parse_results                                               │
normalizer-1  | │                                                                                                  │
normalizer-1  | │    91 │   │   affirmations = []                                                                  │
normalizer-1  | │    92 │   │   scan_profiles = []                                                                 │
normalizer-1  | │    93 │   │                                                                                      │
normalizer-1  | │ ❱  94 │   │   for result in results:                                                             │
normalizer-1  | │    95 │   │   │   match result:                                                                  │
normalizer-1  | │    96 │   │   │   │   case OOI():                                                                │
normalizer-1  | │    97 │   │   │   │   │   oois.append(result)                                                    │
normalizer-1  | │                                                                                                  │
normalizer-1  | │ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
normalizer-1  | │ │    affirmations = []                                                                         │ │
normalizer-1  | │ │    declarations = []                                                                         │ │
normalizer-1  | │ │ normalizer_meta = NormalizerMeta(                                                            │ │
normalizer-1  | │ │                   │   id=UUID('078ec3b5-bce6-4c09-b5b0-f9a7a9c5e869'),                       │ │
normalizer-1  | │ │                   │   started_at=datetime.datetime(2024, 12, 12, 8, 34, 2, 148181,           │ │
normalizer-1  | │ │                   tzinfo=datetime.timezone.utc),                                             │ │
normalizer-1  | │ │                   │   ended_at=datetime.datetime(2024, 12, 12, 8, 34, 2, 148407,             │ │
normalizer-1  | │ │                   tzinfo=datetime.timezone.utc),                                             │ │
normalizer-1  | │ │                   │   raw_data=RawDataMeta(                                                  │ │
normalizer-1  | │ │                   │   │   id=UUID('ae276311-0089-426d-9e99-43f0fae2c003'),                   │ │
normalizer-1  | │ │                   │   │   boefje_meta=BoefjeMeta(                                            │ │
normalizer-1  | │ │                   │   │   │   id=UUID('d08291d7-fd9b-4835-9dfc-2dde76201fcf'),               │ │
normalizer-1  | │ │                   │   │   │   started_at=datetime.datetime(2024, 12, 12, 7, 19, 11, 691374,  │ │
normalizer-1  | │ │                   tzinfo=TzInfo(UTC)),                                                       │ │
normalizer-1  | │ │                   │   │   │   ended_at=datetime.datetime(2024, 12, 12, 7, 19, 11, 691376,    │ │
normalizer-1  | │ │                   tzinfo=TzInfo(UTC)),                                                       │ │
normalizer-1  | │ │                   │   │   │   boefje=Boefje(id='manual', version=None),                      │ │
normalizer-1  | │ │                   │   │   │   input_ooi='Network|internet',                                  │ │
normalizer-1  | │ │                   │   │   │   arguments={},                                                  │ │
normalizer-1  | │ │                   │   │   │   organization='aa',                                             │ │
normalizer-1  | │ │                   │   │   │   runnable_hash=None,                                            │ │
normalizer-1  | │ │                   │   │   │   environment=None                                               │ │
normalizer-1  | │ │                   │   │   ),                                                                 │ │
normalizer-1  | │ │                   │   │   mime_types=[                                                       │ │
normalizer-1  | │ │                   │   │   │   {'value': '/bit/disallowed-csp-hostnames'},                    │ │
normalizer-1  | │ │                   │   │   │   {'value': 'boefje/manual'},                                    │ │
normalizer-1  | │ │                   │   │   │   {'value': 'answer'}                                            │ │
normalizer-1  | │ │                   │   │   ]                                                                  │ │
normalizer-1  | │ │                   │   ),                                                                     │ │
normalizer-1  | │ │                   │   normalizer=Normalizer(id='kat_answer_parser', version=None)            │ │
normalizer-1  | │ │                   )                                                                          │ │
normalizer-1  | │ │            oois = []                                                                         │ │
normalizer-1  | │ │         results = <generator object run at 0x787b49770240>                                   │ │
normalizer-1  | │ │   scan_profiles = []                                                                         │ │
normalizer-1  | │ │            self = <boefjes.local.LocalNormalizerJobRunner object at 0x787b49a717d0>          │ │
normalizer-1  | │ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
normalizer-1  | │                                                                                                  │
normalizer-1  | │ /app/boefjes/boefjes/plugins/kat_answer_parser/normalize.py:11 in run                            │
normalizer-1  | │                                                                                                  │
normalizer-1  | │    8 def run(input_ooi: dict, raw: bytes) -> Iterable[NormalizerOutput]:                         │
normalizer-1  | │    9 │   data = json.loads(raw)                                                                  │
normalizer-1  | │   10 │                                                                                           │
normalizer-1  | │ ❱ 11 │   bit_id = data["schema"].removeprefix("/bit/")                                           │
normalizer-1  | │   12 │                                                                                           │
normalizer-1  | │   13 │   yield Config(ooi=input_ooi["primary_key"], bit_id=bit_id, config=data["answer"])        │
normalizer-1  | │   14                                                                                             │
normalizer-1  | │                                                                                                  │
normalizer-1  | │ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
normalizer-1  | │ │      data = {                                                                                │ │
normalizer-1  | │ │             │   'disallowed_hostnames':                                                      │ │
normalizer-1  | │ │             'githubpages.com,github.io,jsdelivr.com,cdn.skypack.dev,unpkg.com,cloudflare.co… │ │
normalizer-1  | │ │             │   'disallow_url_shorteners': True                                              │ │
normalizer-1  | │ │             }                                                                                │ │
normalizer-1  | │ │ input_ooi = {'primary_key': 'Network|internet'}                                              │ │
normalizer-1  | │ │       raw = b'{"disallowed_hostnames":"githubpages.com,github.io,jsdelivr.com,cdn.skypack.d… │ │
normalizer-1  | │ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
normalizer-1  | ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
normalizer-1  | KeyError: 'schema'
normalizer-1  | Traceback (most recent call last):
normalizer-1  |   File "/app/boefjes/boefjes/app.py", line 251, in _start_working
normalizer-1  |     handler.handle(p_item.data)
normalizer-1  |   File "/app/boefjes/boefjes/job_handler.py", line 199, in handle
normalizer-1  |     results = self.job_runner.run(normalizer_meta, raw)
normalizer-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
normalizer-1  |   File "/app/boefjes/boefjes/local.py", line 86, in run
normalizer-1  |     return self._parse_results(normalizer_meta, results)
normalizer-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
normalizer-1  |   File "/app/boefjes/boefjes/local.py", line 94, in _parse_results
normalizer-1  |     for result in results:
normalizer-1  |   File "/app/boefjes/boefjes/plugins/kat_answer_parser/normalize.py", line 11, in run
normalizer-1  |     bit_id = data["schema"].removeprefix("/bit/")
normalizer-1  |              ~~~~^^^^^^^^^^
normalizer-1  | KeyError: 'schema'
normalizer-1  | HTTP Request: GET http://scheduler:8000/tasks/078ec3b5-bce6-4c09-b5b0-f9a7a9c5e869 "HTTP/1.1 200 OK"
normalizer-1  | HTTP Request: PATCH http://scheduler:8000/tasks/078ec3b5-bce6-4c09-b5b0-f9a7a9c5e869 "HTTP/1.1 200 OK"
normalizer-1  | 2024-12-12T08:34:02.566312 [info] Set status to TaskStatus.FAILED in the scheduler for task[id=078ec3b5-bce6-4c09-b5b0-f9a7a9c5e869]
normalizer-1  | HTTP Request: GET http://scheduler:8000/queues "HTTP/1.1 200 OK"

```

**Comment by noamblitz** [comment]
<img width="1546" alt="Image" src="https://github.com/user-attachments/assets/865977e1-6d58-4828-b440-e0fbd0c52b29" />

I cant reproduce this. Could you give a bit more context on how to reproduce?
