### ISSUE TITLE
XTDB Out-of-memory Java heap space

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#429]
**Describe the bug**
When running KAT 1.6.2 for a few days on multiple organisations, at some point the `findings` and `objects` pages become unreachable, resulting in `Server Error 500` after a timeout of multiple minutes.

**To Reproduce**
1. Run KAT 1.6.2 for a few days (with multiple organisations?)
2. Click on 'objects'
3. Enjoy `Server Error 500`

**Expected behavior**
KAT should quickly load the requested pages.

**OpenKAT version**
1.6.2

**Additional context**
In our case, it looked like the XTDB container crashed due to using more than 1GB of RAM, before its garbage could be properly collected.

Some logs:
```java
WARN  o.e.j.util.thread.QueuedThreadPool - 
java.lang.OutOfMemoryError: Java heap space
07:57:50.189 [qtp857410557-25-acceptor-0@ea59010-ServerConnector@71b38b11{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:3000}] WARN  o.e.jetty.server.AbstractConnector - 
java.lang.OutOfMemoryError: Java heap space
07:57:50.190 [qtp857410557-4736] WARN  org.eclipse.jetty.server.HttpChannel - /_xtdb/z-cert/query
java.lang.IllegalStateException: COMPLETED
	at org.eclipse.jetty.server.HttpChannelState.sendError(HttpChannelState.java:915)
	at org.eclipse.jetty.server.Response.sendError(Response.java:471)
	at juxt.clojars_mirrors.ring_jetty_adapter.v0v14v2.ring.adapter.jetty9$proxy_handler$fn__16448.invoke(jetty9.clj:59)
	at juxt.clojars_mirrors.ring_jetty_adapter.v0v14v2.ring.adapter.jetty9.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Lisser** [comment]
Merged
- https://github.com/minvws/nl-kat-coordination/pull/488

**Comment by dekkers** [comment]
In xtdb-http-multinode v1.0.3 it is also possible to set JVM options to control memory usage to prevent XTDB getting out of memory.
