### ISSUE TITLE
LaTeX font change causes stacktrace

### ISSUE THREAD

**Issue by tobiasBDO** [minvws/nl-kat-coordination#590]
**Describe the bug**
After changing the font in the bevindingenrapport LaTeX file, Keiko encounters errors and cannot create the report

**To Reproduce**
1. Add `\usepackage{helvet} % load Helvetica font` to the `template.tex` file together with `\renewcommand{\familydefault}{\sfdefault} % set Helvetica as default font`
2. Rebuild with `docker-compose up -d --build --force-recreate --no-deps keiko`
3. Generate a new report
4. Download PDF

**Expected behavior**
I expect Keiko to create a report in the requested font.

**OpenKAT version**
Release tag: latest
Installed by downloading the OpenKAT repo and building from scratch. 

**Desktop (please complete the following information if relevant):**
 - OS: Windows 11
 - Browser: Firefox 111.0.1

**Additional context**
```
INFO:     Will watch for changes in these directories: ['/app/keiko/keiko']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [1] using StatReload
[2023-03-28 09:17:19 +0000] [8] [INFO] [logging] [keiko.logging] Logging configuration loaded. [log_cfg=logging.json]
[2023-03-28 09:17:19 +0000] [8] [INFO] [templates] [keiko.templates] Loading samples in folder: /app/keiko/templates
INFO:     Started server process [8]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     172.19.0.16:49330 - "POST /reports HTTP/1.1" 200 OK
[2023-03-28 09:17:28 +0000] [8] [INFO] [keiko] [keiko.keiko] Data shape validation successful. [report_id=0e9c870c] [template=bevindingenrapport]
[2023-03-28 09:17:28 +0000] [8] [INFO] [keiko] [keiko.keiko] Glossary loaded. [report_id=0e9c870c] [glossary=dutch.hiero.csv]
[2023-03-28 09:17:28 +0000] [8] [INFO] [keiko] [keiko.keiko] Template rendered. [report_id=0e9c870c] [template=bevindingenrapport]
[2023-03-28 09:17:28 +0000] [8] [INFO] [keiko] [keiko.keiko] Temporary folder created. [report_id=0e9c870c] [template=bevindingenrapport] [tmp_dirname=/tmp/tmpb9wjp8va]
[2023-03-28 09:17:28 +0000] [8] [INFO] [keiko] [keiko.keiko] Assets copied. [report_id=0e9c870c] [template=bevindingenrapport]
INFO:     172.19.0.16:49330 - "GET /0e9c870c.keiko.pdf HTTP/1.1" 404 Not Found
[2023-03-28 09:17:30 +0000] [8] [INFO] [keiko] [keiko.keiko] pdflatex run. [report_id=0e9c870c] [template=bevindingenrapport] [command=pdflatex -synctex=1 -interaction=nonstopmode 0e9c870c.keiko.tex]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 68, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 170, in __call__
    await self.background()
  File "/usr/local/lib/python3.8/site-packages/starlette/background.py", line 43, in __call__
    await task()
  File "/usr/local/lib/python3.8/site-packages/starlette/background.py", line 28, in __call__
    await run_in_threadpool(self.func, *self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/keiko/./keiko/keiko.py", line 129, in generate_report
    raise Exception("Error running pdflatex")
Exception: Error running pdflatex
INFO:     172.19.0.16:49340 - "GET /0e9c870c.keiko.pdf HTTP/1.1" 404 Not Found
INFO:     172.19.0.16:49350 - "GET /0e9c870c.keiko.pdf HTTP/1.1" 404 Not Found
INFO:     172.19.0.16:49366 - "GET /0e9c870c.keiko.pdf HTTP/1.1" 404 Not Found
INFO:     172.19.0.16:53926 - "GET /0e9c870c.keiko.pdf HTTP/1.1" 404 Not Found
INFO:     172.19.0.16:53940 - "GET /0e9c870c.keiko.pdf HTTP/1.1" 404 Not Found
```

**Comment by praseodym** [comment]
Thanks for the PR (#593)! It is a big improvement over the current situation.

As an alternative, maybe even better approach we could consider switching to XeLaTeX or LuaLaTeX; both support TrueType and OpenType fonts as well as UTF-8. TrueType and OpenType support will make it easier to use a custom corporate identity font, and proper UTF-8 support will solve various encoding issues. 

We can use XeLaTeX from TeX Live (packaged in Debian) or can consider using [Tectonic](https://tectonic-typesetting.github.io).
