### ISSUE TITLE
Webpage capture Boefje fails consistently

### ISSUE THREAD

**Issue by Darwinkel** [minvws/nl-kat-coordination#804]
**Describe the bug**
The last couple of weeks(?) the webpage-capture Boefje has been failing. Both when automatically scheduled, manually run, and with multiple websites.

 The logs show the following:

```
[2023-04-25 07:15:48 +0000] [8] [INFO] [job_handler] Handling boefje webpage-capture[276fff8fa4c44d33a2bea84d88a8e10d]
2023-04-25T07:15:48.357331315Z [2023-04-25 07:15:48 +0000] [8] [INFO] [job_handler] Starting boefje webpage-capture[276fff8fa4c44d33a2bea84d88a8e10d]
2023-04-25T07:15:48.357346645Z [2023-04-25 07:15:48 +0000] [8] [INFO] [local] Running local boefje plugin
2023-04-25T07:15:51.872375990Z [2023-04-25 07:15:51 +0000] [8] [WARNING] [main] [Webpage Capture] HAR (.har.zip) and Storage (.json) files not working in 1.30.0.
2023-04-25T07:15:51.900750058Z [2023-04-25 07:15:51 +0000] [8] [WARNING] [main] [Webpage Capture] /tmp/tmp.png not found in container a94ec31e7f63 ['mcr.microsoft.com/playwright:v1.30.0-focal']
2023-04-25T07:15:51.923009799Z [2023-04-25 07:15:51 +0000] [8] [ERROR] [job_handler] Error running boefje webpage-capture[276fff8fa4c44d33a2bea84d88a8e10d]
2023-04-25T07:15:51.923020321Z Traceback (most recent call last):
2023-04-25T07:15:51.923022009Z   File "/app/boefjes/boefjes/local.py", line 50, in run
2023-04-25T07:15:51.923023387Z     return boefje_resource.module.run(boefje_meta)
2023-04-25T07:15:51.923024669Z   File "/app/boefjes/boefjes/plugins/kat_webpage_capture/main.py", line 111, in run
2023-04-25T07:15:51.923025960Z     image_bytes, har_zip, storage_json = run_playwright(webpage=webpage, browser=BROWSER)
2023-04-25T07:15:51.923027224Z   File "/app/boefjes/boefjes/plugins/kat_webpage_capture/main.py", line 98, in run_playwright
2023-04-25T07:15:51.923028544Z     image = Image.open(io.BytesIO(get_file_from_container(container=res, path=f"{tmp_path}.png")))
2023-04-25T07:15:51.923029876Z   File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 3283, in open
2023-04-25T07:15:51.923031155Z     raise UnidentifiedImageError(msg)
2023-04-25T07:15:51.923032359Z PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fc461bc2220>
2023-04-25T07:15:51.923033797Z 
2023-04-25T07:15:51.923034937Z The above exception was the direct cause of the following exception:
2023-04-25T07:15:51.923036187Z 
2023-04-25T07:15:51.923037294Z Traceback (most recent call last):
2023-04-25T07:15:51.923038454Z   File "/app/boefjes/boefjes/job_handler.py", line 138, in handle
2023-04-25T07:15:51.923039681Z     boefje_results = self.job_runner.run(boefje_meta, environment)
2023-04-25T07:15:51.923040875Z   File "/app/boefjes/boefjes/local.py", line 52, in run
2023-04-25T07:15:51.923042111Z     raise JobRuntimeError("Boefje failed") from e
2023-04-25T07:15:51.923043350Z boefjes.runtime_interfaces.JobRuntimeError: Boefje failed
2023-04-25T07:15:51.923044612Z [2023-04-25 07:15:51 +0000] [8] [INFO] [job_handler] Saving to Bytes for boefje boefje webpage-capture[276fff8fa4c44d33a2bea84d88a8e10d]
2023-04-25T07:15:52.399542844Z [2023-04-25 07:15:52 +0000] [8] [INFO] [job_handler] Done with boefje for webpage-capture[276fff8fa4c44d33a2bea84d88a8e10d]
2023-04-25T07:15:52.399643289Z [2023-04-25 07:15:52 +0000] [8] [ERROR] [app] An error occurred handling scheduler item 276fff8fa4c44d33a2bea84d88a8e10d
2023-04-25T07:15:52.399645579Z Traceback (most recent call last):
2023-04-25T07:15:52.399646772Z   File "/app/boefjes/boefjes/local.py", line 50, in run
2023-04-25T07:15:52.399648024Z     return boefje_resource.module.run(boefje_meta)
2023-04-25T07:15:52.399649261Z   File "/app/boefjes/boefjes/plugins/kat_webpage_capture/main.py", line 111, in run
2023-04-25T07:15:52.399657134Z     image_bytes, har_zip, storage_json = run_playwright(webpage=webpage, browser=BROWSER)
2023-04-25T07:15:52.399658399Z   File "/app/boefjes/boefjes/plugins/kat_webpage_capture/main.py", line 98, in run_playwright
2023-04-25T07:15:52.399659584Z     image = Image.open(io.BytesIO(get_file_from_container(container=res, path=f"{tmp_path}.png")))
2023-04-25T07:15:52.399660811Z   File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 3283, in open
2023-04-25T07:15:52.399661995Z     raise UnidentifiedImageError(msg)
2023-04-25T07:15:52.399663089Z PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fc461bc2220>
2023-04-25T07:15:52.399664458Z 
2023-04-25T07:15:52.399665494Z The above exception was the direct cause of the following exception:
2023-04-25T07:15:52.399666618Z 
2023-04-25T07:15:52.399667650Z Traceback (most recent call last):
2023-04-25T07:15:52.399668806Z   File "/app/boefjes/boefjes/app.py", line 101, in start_working
2023-04-25T07:15:52.399669987Z     item_handler.handle(p_item.data)
2023-04-25T07:15:52.399671026Z   File "/app/boefjes/boefjes/job_handler.py", line 138, in handle
2023-04-25T07:15:52.399672193Z     boefje_results = self.job_runner.run(boefje_meta, environment)
2023-04-25T07:15:52.399673300Z   File "/app/boefjes/boefjes/local.py", line 52, in run
2023-04-25T07:15:52.399674692Z     raise JobRuntimeError("Boefje failed") from e
2023-04-25T07:15:52.399676672Z boefjes.runtime_interfaces.JobRuntimeError: Boefje failed
2023-04-25T07:15:52.399868692Z [2023-04-25 07:15:52 +0000] [8] [INFO] [app] Patching scheduler task task[276fff8fa4c44d33a2bea84d88a8e10d] to failed
2023-04-25T07:15:52.406946139Z [2023-04-25 07:15:52 +0000] [8] [INFO] [scheduler_client] Set task status to TaskStatus.FAILED in the scheduler for task[276fff8f-a4c4-4d33-a2be-a84d88a8e10d]
2023-04-25T07:15:53.426790411Z
```

**To Reproduce**
1. Add some HostnameHTTPURL objects
2. Run the webpage capture Boefje on it
3. See error in /tasks and the Boefje logs

**Expected behavior**
We either way remove/disable the webpage-capture boefje, or we fix it such that it works.

**Screenshots**
![image](https://user-images.githubusercontent.com/9536436/234202474-8f659902-2487-4a85-b789-d927c26dcb1b.png)

**Comment by ammar92** [comment]
Looks like there are no images captured or saved and the boefje fails to load the image. Could be a connection or write access problem? Whatever caused it, there should be proper error handling when trying to read/ open that file from the container.

I can have a look at this later
