### ISSUE TITLE
When deleting multiple organizations in rapid succession, the scheduler might crash

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#987]
**Describe the bug**
When deleting multiple organizations in rapid succession, the scheduler might crash due to a modified dict during looping over the organizations that need their workers stopped

**To Reproduce**
1. Delete two or more organizations at once
2. Wait for the scheduler to start cleaning up
3. Notice the error mentioning a dict changed size while iterating it.

**Expected behavior**
Cleanly delete both organizations and stop all related workers

**Logs**
May  9 13:34:48 scheduler-1 scheduler-scheduler-app[482]: [2023-05-09 13:34:48 +0200] [482] [INFO] [scheduler] [scheduler.schedulers.normalizer] Stopped scheduler: normalizer-X
May  9 13:34:48 scheduler-1 scheduler-scheduler-app[482]: [2023-05-09 13:34:48 +0200] [482] [INFO] [scheduler] [scheduler.schedulers.normalizer] Stopped scheduler: normalizer-Y
May  9 13:34:48 scheduler-1 scheduler-scheduler-app[482]: [2023-05-09 13:34:48 +0200] [482] [INFO] [app] [scheduler.app] Removed 2 organisations from scheduler [org_ids={'X', 'Y'}]
May  9 13:34:48 scheduler-1 scheduler-scheduler-app[482]: [2023-05-09 13:34:48 +0200] [482] [INFO] [scheduler] [scheduler.schedulers.normalizer] Stopped scheduler: normalizer-X

May  9 13:34:48 scheduler-1 scheduler-scheduler-app[482]: Traceback (most recent call last):
May  9 13:34:48 scheduler-1 scheduler-scheduler-app[482]:  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
May  9 13:34:48 scheduler-1 scheduler-scheduler-app[482]:    return _run_code(code, main_globals, None,
May  9 13:34:48 scheduler-1 scheduler-scheduler-app[482]:  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
May  9 13:34:48 scheduler-1 scheduler-scheduler-app[482]:    exec(code, run_globals)
May  9 13:34:48 scheduler-1 scheduler-scheduler-app[482]:  File "/var/www/scheduler_v1.7.1/scheduler/__main__.py", line 7, in <module>
May  9 13:34:48 scheduler-1 scheduler-scheduler-app[482]:    app.run()
May  9 13:34:48 scheduler-1 scheduler-scheduler-app[482]:  File "/var/www/scheduler_v1.7.1/scheduler/app.py", line 259, in run
May  9 13:34:48 scheduler-1 scheduler-scheduler-app[482]:    self.shutdown()
May  9 13:34:48 scheduler-1 scheduler-scheduler-app[482]:  File "/var/www/scheduler_v1.7.1/scheduler/app.py", line 66, in shutdown
May  9 13:34:48 scheduler-1 scheduler-scheduler-app[482]:    for s in self.schedulers.values():
May  9 13:34:48 scheduler-1 scheduler-scheduler-app[482]: RuntimeError: dictionary changed size during iteration

**OpenKAT version**
1.7 and up, possible older versions too.

**Additional context**
When later recreating these organizations, their workers are never started and scheduling wont begin until the scheduler daemons are restarted. Subsequently events in the rabbitMQ will then be handled in a `first come first serve` order much later than anticipated.

**Comment by ammar92** [comment]
Interesting. Either a bug within the `for` clause that mutates the dictionary object, or multiple threads accessing the same (unlocked) resource

**Comment by jpbruinsslot** [comment]
By the suggestion of @ammar92 I'm implementing a callback functionality, such that the scheduler can clean itself up.
